// The dedicated AI Analyst (Spotter-style conversational analysis).
//
// An analyst is a pinned (reasoning model, data scope) pair. Each question
// runs a TRANSPARENT loop — every stage of which is stored and shown:
//
//   1. PLAN        one LLM call decomposes the question into 1–4 concrete
//                  analysis steps ("approach" paragraph + step goals)
//   2. QUERY       each step's SQL is generated by the SAME battle-tested
//                  generator the BI analyst uses (biAgent.generateSql, with
//                  its engine-error repair pass) and executed on the
//                  analyst's data scope
//   3. SELF-CHECK  one LLM call reviews every step's result against its
//                  goal — sanity of magnitudes, empty results, suspicious
//                  shapes — and may return corrected SQL, which re-runs
//   4. SYNTHESIZE  one LLM call writes the final answer FROM the step
//                  results (never from imagination), citing steps by number
//
// The trace (approach, per-step SQL, trimmed result samples, check
// verdicts, answer) IS the product: it renders in the thread, persists to
// ai_analyst_threads, and exports to PDF. Explainability here means the
// reader can re-run any step's SQL and get the same numbers.
//
// Pure pieces (prompt builders, parsers, trimming, the reasoning-model
// heuristic) are exported and unit-tested directly — tests call THESE, not
// re-implementations.
import {
  describeResultFacts,
  describeSchema,
  ensureGovernedCatalog,
  generateSql,
  llmJson,
  suggestChart,
  type BiPlan,
  type ChartSpec,
  type SavedMetric,
  type SemanticEntry,
} from "@/lib/biAgent";
import type { DatasetMeta, QueryResult } from "@/lib/sqlEngine";

// ── Types ────────────────────────────────────────────────────────────────

export type AnalystSource =
  | { kind: "local"; tables: string[] } // empty tables = every local dataset
  | { kind: "warehouse"; connection_id: string };

export type AnalystCheckVerdict = "pass" | "refined" | "suspect";

export type AnalystStep = {
  goal: string;
  sql?: string;
  columns?: string[];
  /** Trimmed result sample (ANALYST_ROW_CAP rows) — the trace, not a store. */
  rows?: Record<string, unknown>[];
  /** True row count before trimming. */
  rowCount?: number;
  check?: { verdict: AnalystCheckVerdict; note: string };
  error?: string;
  status: "pending" | "writing_sql" | "running" | "checking" | "done" | "error";
};

export type AnalystTurn = {
  question: string;
  /** The analyst's stated approach — shown before any query runs. */
  approach?: string;
  steps: AnalystStep[];
  /** Final synthesis, markdown. */
  answer?: string;
  chart?: ChartSpec;
  /** Which step the chart draws (index into steps). */
  chartStep?: number;
  status: "planning" | "working" | "checking" | "synthesizing" | "done" | "error";
  error?: string;
  at?: string;
};

// ── Limits ───────────────────────────────────────────────────────────────

/** Most questions decompose into 2–3 queries; more is a sign of drift. */
export const MAX_ANALYSIS_STEPS = 4;

/** Rows kept per step in the stored trace (same discipline as widgets). */
export const ANALYST_ROW_CAP = 50;

/** Prior Q/A pairs carried into the next question's context. */
export const ANALYST_MEMORY_TURNS = 4;

/**
 * Completion budgets, sized for REASONING models — which is what this
 * feature tells you to pick.
 *
 * A reasoning model's thinking tokens are charged against the completion
 * cap, so a budget sized for the visible answer starves the invisible part
 * and the model returns nothing at all. Measured: gpt-5-mini, planning a
 * three-part discount question with a 1,200 cap, spent 1,152 completion
 * tokens and returned `{}` — 25 seconds, real money, and a user-facing
 * "returned no analysis steps". These are deliberately generous; the plan
 * and check replies are small, so the headroom is spent on thinking, not on
 * output nobody reads.
 */
export const ANALYST_TOKENS = { plan: 6000, check: 8000, synthesis: 8000 } as const;

// ── Reasoning-model heuristic (the create dialog's nudge) ────────────────

// Families marketed and benchmarked as reasoning/thinking models. The
// dialog SUGGESTS one of these; it never blocks — the list is a heuristic
// over provider ids, not a gate, and new model names appear monthly.
const REASONING_MODEL_RE =
  /(^|[/:.-])o[134](\b|-)|gpt-5|deepseek-r1|\bqwq\b|thinking|reasoner|reasoning|claude-(fable|mythos|opus)|(opus|sonnet)-[45]|claude-[45]|gemini-[23][.-]5-pro|grok-[34]/i;

export function isReasoningModelId(id: string): boolean {
  return REASONING_MODEL_RE.test(id);
}

// ── Pure helpers ─────────────────────────────────────────────────────────

/** SELECT/WITH only, one statement — applied to every SQL before it runs. */
export function assertSelectOnly(sql: string): string {
  const s = sql.trim().replace(/;\s*$/, "");
  if (!/^(select|with)\b/i.test(s)) {
    throw new Error("The analyst may only run SELECT statements.");
  }
  if (s.includes(";")) {
    throw new Error("The analyst may only run a single statement.");
  }
  return s;
}

/** Cap a step's stored rows; everything else in the trace is kept. */
export function trimStepForStorage(step: AnalystStep): AnalystStep {
  if (!step.rows || step.rows.length <= ANALYST_ROW_CAP) return step;
  return { ...step, rows: step.rows.slice(0, ANALYST_ROW_CAP) };
}

export function trimTurnForStorage(turn: AnalystTurn): AnalystTurn {
  return { ...turn, steps: turn.steps.map(trimStepForStorage) };
}

/** Compact Q→A lines from prior turns, for conversational continuity. */
export function priorContext(turns: AnalystTurn[], max = ANALYST_MEMORY_TURNS): string {
  const done = turns.filter((t) => t.status === "done" && t.answer);
  const recent = done.slice(-max);
  if (recent.length === 0) return "";
  const lines = recent.map(
    (t) => `Q: ${t.question}\nA: ${(t.answer ?? "").slice(0, 500).replace(/\s+/g, " ")}`,
  );
  return `EARLIER IN THIS ANALYSIS:\n${lines.join("\n")}\n`;
}

// ── Prompts (pure, exported so tests read what the app actually sends) ───

export function buildAnalysisPlanPrompt(args: {
  schema: string;
  question: string;
  prior: string;
}): { systemPrompt: string; userPrompt: string } {
  return {
    systemPrompt:
      "You are a senior data analyst planning an analysis. Decompose the question into the " +
      `SMALLEST set of concrete SQL-answerable steps (1-${MAX_ANALYSIS_STEPS}) over the ` +
      "provided schema. Each step is one query's worth of work with a measurable goal — " +
      '"total sales by region", not "explore the data". Prefer ONE step when one query ' +
      "answers the question; add steps only when the answer genuinely needs several angles " +
      "(a total plus a breakdown, a trend plus its outliers, a comparison of two segments). " +
      "Only use tables and columns that exist in the schema. Do not write SQL here.",
    userPrompt:
      `${args.schema}\n\n${args.prior}QUESTION: ${args.question}\n\n` +
      `Return JSON: { "approach": "1-3 sentences on how you'll answer and why these steps", ` +
      `"steps": [ { "goal": "concrete, measurable step goal" } ] }`,
  };
}

export function buildCheckPrompt(args: {
  question: string;
  steps: Array<{ goal: string; sql?: string; facts: string; error?: string }>;
}): { systemPrompt: string; userPrompt: string } {
  const stepBlocks = args.steps
    .map(
      (s, i) =>
        `STEP ${i + 1}: ${s.goal}\nSQL: ${s.sql ?? "(none)"}\n` +
        (s.error ? `ENGINE ERROR: ${s.error}` : `RESULT FACTS: ${s.facts}`),
    )
    .join("\n\n");
  return {
    systemPrompt:
      "You are the same analyst REVIEWING YOUR OWN WORK before presenting it. For each step, " +
      "judge whether its result actually answers its goal: empty results for questions that " +
      "should have data, totals of the wrong magnitude, groupings split by case variants, a " +
      "LIMIT that cut a ranking short, nulls sorted to the top, the wrong column. " +
      'Verdicts: "pass" (result answers the goal), "suspect" (present the result but flag ' +
      'the concern in the note). If a step is WRONG and you can fix it, return "refined_sql" ' +
      "with a corrected single SELECT statement — it will be re-executed and replace the " +
      "result. Be specific in notes: name the number or shape that concerns you. Never " +
      "invent data.",
    userPrompt:
      `QUESTION: ${args.question}\n\n${stepBlocks}\n\n` +
      `Return JSON: { "checks": [ { "verdict": "pass|suspect", "note": "one sentence", ` +
      `"refined_sql": "SELECT ... (only when correcting)" } ], ` +
      `"headline": <index of the step whose result best answers the question, 0-based> }`,
  };
}

export function buildSynthesisPrompt(args: {
  question: string;
  approach: string;
  prior: string;
  steps: Array<{ goal: string; facts: string; verdict?: string; note?: string; error?: string }>;
}): { systemPrompt: string; userPrompt: string } {
  const stepBlocks = args.steps
    .map(
      (s, i) =>
        `STEP ${i + 1}: ${s.goal}\n` +
        (s.error
          ? `FAILED: ${s.error}`
          : `RESULT: ${s.facts}${s.verdict ? `\nCHECK: ${s.verdict}${s.note ? ` — ${s.note}` : ""}` : ""}`),
    )
    .join("\n\n");
  return {
    systemPrompt:
      "You are a senior data analyst writing up findings. Answer the question using ONLY the " +
      "step results below — every number in your answer must appear in a step result, cited " +
      "like (step 2). Lead with the direct answer, then the supporting evidence, then any " +
      "caveat a careful analyst would add (suspect checks, failed steps, sample caps). " +
      "Markdown, short paragraphs and lists, no headings. If the steps do not answer the " +
      "question, say exactly what is missing instead of guessing.",
    userPrompt:
      `${args.prior}QUESTION: ${args.question}\nAPPROACH: ${args.approach}\n\n${stepBlocks}\n\n` +
      `Return JSON: { "answer": "markdown" }`,
  };
}

// ── Parsers (validated, exported) ────────────────────────────────────────

export function parseAnalysisPlan(raw: unknown): { approach: string; steps: { goal: string }[] } {
  // Tolerant by measurement, like parseSynthesis: models in JSON mode wrap
  // the plan, name the goal key differently, or return plain strings.
  const root = (raw ?? {}) as Record<string, unknown>;
  const o = (root.plan && typeof root.plan === "object" ? root.plan : root) as Record<
    string,
    unknown
  >;
  const approach = typeof o.approach === "string" ? o.approach.trim() : "";
  const list = Array.isArray(o.steps)
    ? o.steps
    : Array.isArray(o.analysis_steps)
      ? o.analysis_steps
      : ((Object.values(o).find(Array.isArray) as unknown[] | undefined) ?? []);
  const goalOf = (s: unknown): string => {
    if (typeof s === "string") return s.trim();
    const obj = (s ?? {}) as Record<string, unknown>;
    for (const k of ["goal", "step", "description", "title", "objective", "name"]) {
      if (typeof obj[k] === "string" && (obj[k] as string).trim()) return (obj[k] as string).trim();
    }
    return "";
  };
  const steps = list
    .map((s) => ({ goal: goalOf(s) }))
    .filter((s) => s.goal.length > 0)
    .slice(0, MAX_ANALYSIS_STEPS);
  if (steps.length === 0) {
    // An EMPTY reply and a badly-shaped one are different failures, and the
    // empty one has a specific cause worth naming: a reasoning model that
    // spent its whole completion budget thinking. Saying "try rephrasing"
    // for that sends the user to fix the one thing that was fine.
    if (Object.keys(root).length === 0) {
      throw new Error(
        "The model returned an empty plan — it likely spent its completion budget on reasoning. " +
          "Try a question with fewer parts, or an analyst on a model with more headroom.",
      );
    }
    throw new Error("The analyst returned no analysis steps — try rephrasing the question.");
  }
  return { approach, steps };
}

/**
 * The synthesis reply, tolerantly. Models in JSON mode legitimately return a
 * bare JSON string (JSON.parse('"text"') succeeds), or wrap the markdown
 * under a key other than "answer" — measured live with gpt-5-mini, whose
 * write-up came back shaped so the strict `.answer` read produced the
 * "no write-up" fallback on a perfectly good analysis.
 */
export function parseSynthesis(raw: unknown): string {
  if (typeof raw === "string") return raw.trim();
  const o = (raw ?? {}) as Record<string, unknown>;
  for (const k of ["answer", "markdown", "text", "findings", "summary"]) {
    if (typeof o[k] === "string" && (o[k] as string).trim()) return (o[k] as string).trim();
  }
  // A single string value under an unexpected key is still the answer.
  const strings = Object.values(o).filter(
    (v): v is string => typeof v === "string" && v.trim().length > 0,
  );
  return strings.length === 1 ? strings[0].trim() : "";
}

export function parseCheckResponse(
  raw: unknown,
  stepCount: number,
): {
  checks: Array<{ verdict: "pass" | "suspect"; note: string; refined_sql?: string }>;
  headline: number;
} {
  const o = (raw ?? {}) as { checks?: unknown; headline?: unknown };
  const list = Array.isArray(o.checks) ? o.checks : [];
  const checks = Array.from({ length: stepCount }, (_, i) => {
    const c = (list[i] ?? {}) as { verdict?: unknown; note?: unknown; refined_sql?: unknown };
    const verdict = c.verdict === "suspect" ? ("suspect" as const) : ("pass" as const);
    const note = typeof c.note === "string" ? c.note.trim() : "";
    const refined =
      typeof c.refined_sql === "string" && c.refined_sql.trim().length > 0
        ? c.refined_sql.trim()
        : undefined;
    return { verdict, note, ...(refined ? { refined_sql: refined } : {}) };
  });
  const h = typeof o.headline === "number" ? Math.trunc(o.headline) : 0;
  const headline = h >= 0 && h < stepCount ? h : 0;
  return { checks, headline };
}

// ── The loop ─────────────────────────────────────────────────────────────

export async function runAnalystTurn(args: {
  question: string;
  datasets: DatasetMeta[];
  semantics: Map<string, SemanticEntry>;
  metrics: SavedMetric[];
  /** Prior turns of THIS thread, for conversational continuity. */
  priorTurns: AnalystTurn[];
  /** Encoded "provider::model" choice — the analyst's pinned model. */
  model?: string;
  /** Override SQL execution (warehouse scope); omitted = local DuckDB. */
  execute?: (sql: string) => Promise<QueryResult>;
  /** Human name of the engine when `execute` is provided. */
  dialect?: string;
  onUpdate: (turn: AnalystTurn) => void;
}): Promise<AnalystTurn> {
  const turn: AnalystTurn = {
    question: args.question,
    steps: [],
    status: "planning",
    at: new Date().toISOString(),
  };
  const emit = () => args.onUpdate({ ...turn, steps: turn.steps.map((s) => ({ ...s })) });
  emit();

  const runSql = async (sql: string): Promise<QueryResult> => {
    const clean = assertSelectOnly(sql);
    return args.execute
      ? await args.execute(clean)
      : await (await import("@/lib/sqlEngine")).runQuery(clean);
  };
  const captureResult = (step: AnalystStep, res: QueryResult) => {
    step.columns = res.columns;
    step.rowCount = res.rows.length;
    step.rows = res.rows.slice(0, ANALYST_ROW_CAP);
  };
  // Facts are described from the FULL result, then the step keeps a capped
  // sample — the check must see true magnitudes, the store must stay small.
  const results: (QueryResult | null)[] = [];

  try {
    // 1. PLAN
    await ensureGovernedCatalog();
    const schema = describeSchema(args.datasets, args.semantics, args.metrics);
    const prior = priorContext(args.priorTurns);
    const planPrompt = buildAnalysisPlanPrompt({ schema, question: args.question, prior });
    const plan = parseAnalysisPlan(
      await llmJson<unknown>({ ...planPrompt, model: args.model, maxTokens: ANALYST_TOKENS.plan }),
    );
    turn.approach = plan.approach;
    turn.steps = plan.steps.map((s) => ({ goal: s.goal, status: "pending" as const }));
    turn.status = "working";
    emit();

    // 2. QUERY each step (sequentially — the trace reads top to bottom)
    for (let i = 0; i < turn.steps.length; i++) {
      const step = turn.steps[i];
      step.status = "writing_sql";
      emit();
      const stepPlan: BiPlan = {
        intent: `One step of a larger analysis. Overall question: ${args.question}`,
        tables: [],
        metrics: [],
        breakdowns: [],
      };
      try {
        step.sql = await generateSql({
          question: step.goal,
          plan: stepPlan,
          datasets: args.datasets,
          semantics: args.semantics,
          metrics: args.metrics,
          dialect: args.dialect,
          localEngine: args.execute ? undefined : "duckdb",
          model: args.model,
        });
        step.status = "running";
        emit();
        let res: QueryResult;
        try {
          res = await runSql(step.sql);
        } catch (e) {
          // One repair pass with the engine's own error, like the BI analyst.
          step.sql = await generateSql({
            question: step.goal,
            plan: stepPlan,
            datasets: args.datasets,
            semantics: args.semantics,
            metrics: args.metrics,
            dialect: args.dialect,
            localEngine: args.execute ? undefined : "duckdb",
            model: args.model,
            repair: { sql: step.sql, error: (e as Error).message },
          });
          emit();
          res = await runSql(step.sql);
        }
        captureResult(step, res);
        results[i] = res;
        step.status = "done";
      } catch (e) {
        step.error = (e as Error).message;
        step.status = "error";
        results[i] = null;
      }
      emit();
    }
    if (turn.steps.every((s) => s.status === "error")) {
      throw new Error(`Every analysis step failed — last error: ${turn.steps.at(-1)?.error}`);
    }

    // 3. SELF-CHECK (one call across all steps; refined SQL re-executes)
    turn.status = "checking";
    turn.steps.forEach((s) => {
      if (s.status === "done") s.status = "checking";
    });
    emit();
    const checkPrompt = buildCheckPrompt({
      question: args.question,
      steps: turn.steps.map((s, i) => ({
        goal: s.goal,
        sql: s.sql,
        facts: results[i] ? describeResultFacts(results[i]!) : "(no result)",
        error: s.error,
      })),
    });
    let headline = 0;
    try {
      const checked = parseCheckResponse(
        await llmJson<unknown>({
          ...checkPrompt,
          model: args.model,
          maxTokens: ANALYST_TOKENS.check,
        }),
        turn.steps.length,
      );
      headline = checked.headline;
      for (let i = 0; i < turn.steps.length; i++) {
        const step = turn.steps[i];
        const c = checked.checks[i];
        if (step.status === "error") continue;
        if (c.refined_sql) {
          try {
            const res = await runSql(c.refined_sql);
            step.sql = c.refined_sql;
            captureResult(step, res);
            results[i] = res;
            step.check = { verdict: "refined", note: c.note || "Corrected on self-review." };
          } catch (e) {
            // The refinement itself failed — keep the original result and
            // surface the concern rather than losing a working answer.
            step.check = {
              verdict: "suspect",
              note: `${c.note || "Self-review proposed a correction"} (correction failed: ${(e as Error).message})`,
            };
          }
        } else {
          step.check = { verdict: c.verdict, note: c.note };
        }
        step.status = "done";
      }
    } catch {
      // A failed check call must not sink a finished analysis: present the
      // results unchecked and SAY so, never silently pretend they passed.
      turn.steps.forEach((s) => {
        if (s.status === "checking") {
          s.status = "done";
          s.check = { verdict: "suspect", note: "Self-check unavailable for this run." };
        }
      });
    }
    emit();

    // 4. SYNTHESIZE + headline chart
    turn.status = "synthesizing";
    emit();
    const synthPrompt = buildSynthesisPrompt({
      question: args.question,
      approach: turn.approach ?? "",
      prior,
      steps: turn.steps.map((s, i) => ({
        goal: s.goal,
        facts: results[i] ? describeResultFacts(results[i]!) : "(no result)",
        verdict: s.check?.verdict,
        note: s.check?.note,
        error: s.error,
      })),
    });
    const headlineResult = results[headline] ?? results.find((r) => r) ?? null;
    const [synth, chart] = await Promise.all([
      llmJson<unknown>({ ...synthPrompt, model: args.model, maxTokens: ANALYST_TOKENS.synthesis }),
      headlineResult
        ? suggestChart({
            question: args.question,
            result: headlineResult,
            plan: { intent: args.question, tables: [], metrics: [], breakdowns: [] },
            model: args.model,
          }).catch(() => undefined)
        : Promise.resolve(undefined),
    ]);
    turn.answer =
      parseSynthesis(synth) ||
      "The analysis completed but produced no write-up — the step results above stand on their own.";
    if (chart) {
      turn.chart = chart;
      turn.chartStep = results[headline] ? headline : results.findIndex((r) => r);
    }
    turn.status = "done";
    emit();
    return turn;
  } catch (e) {
    turn.error = (e as Error).message;
    turn.status = "error";
    emit();
    return turn;
  }
}
