// The dedicated AI Analyst (Spotter-style conversational analysis).
//
// An analyst is a pinned (reasoning model, data scope) pair. Each question
// runs a TRANSPARENT loop — every stage of which is stored and shown:
//
//   1. PLAN        one LLM call decomposes the question into 1–4 concrete
//                  analysis steps ("approach" paragraph + step goals)
//   2. QUERY       each step's SQL is generated by the SAME battle-tested
//                  generator the BI analyst uses (biAgent.generateSql, with
//                  its engine-error repair pass) and executed on the
//                  analyst's data scope
//   3. SELF-CHECK  one LLM call reviews every step's result against its
//                  goal — sanity of magnitudes, empty results, suspicious
//                  shapes — and may return corrected SQL, which re-runs
//   4. SYNTHESIZE  one LLM call writes the final answer FROM the step
//                  results (never from imagination), citing steps by number
//
// The trace (approach, per-step SQL, trimmed result samples, check
// verdicts, answer) IS the product: it renders in the thread, persists to
// ai_analyst_threads, and exports to PDF. Explainability here means the
// reader can re-run any step's SQL and get the same numbers.
//
// Pure pieces (prompt builders, parsers, trimming, the reasoning-model
// heuristic) are exported and unit-tested directly — tests call THESE, not
// re-implementations.
import {
  ANALYST_STEP_CONCURRENCY,
  createTurnCache,
  mapWithConcurrency,
  resultCacheKey,
} from "@/lib/analystParallel";
import {
  describeResultFacts,
  describeSchema,
  ensureGovernedCatalog,
  generateSql,
  llmJson,
  suggestChart,
  type LlmJsonFn,
  type BiPlan,
  type ChartSpec,
  type SavedMetric,
  type SemanticEntry,
} from "@/lib/biAgent";
import {
  analyseDrivers,
  describeDrivers,
  driverInputsFrom,
  type DriverAnalysis,
} from "@/lib/analystDrivers";
import { describeSeries, forecastSeries, readSeries, seriesFrom } from "@/lib/analystSeries";
import type { DatasetMeta, QueryResult } from "@/lib/sqlEngine";
import type { SemanticFilter, SemanticQuery, TimeGrain } from "@/lib/semanticLayer";
import type { MetricDelta, ScenarioChange, ScenarioParameter } from "@/lib/analystScenario";
import type { TurnVerification } from "@/lib/analystVerification";

// ── Types ────────────────────────────────────────────────────────────────

export type AnalystSource =
  | { kind: "local"; tables: string[] } // empty tables = every local dataset
  | { kind: "warehouse"; connection_id: string };

export type AnalystCheckVerdict = "pass" | "refined" | "suspect";

export type AnalystStep = {
  goal: string;
  sql?: string;
  columns?: string[];
  /** Trimmed result sample (ANALYST_ROW_CAP rows) — the trace, not a store. */
  rows?: Record<string, unknown>[];
  /** True row count before trimming. */
  rowCount?: number;
  /**
   * This step's own visual.
   *
   * An analysis that ran three queries has three things to show; charting
   * only the headline threw the other two away and left the reader a table
   * of numbers to squint at. Every step whose result has a chartable SHAPE
   * gets its own chart — `{ type: "table" }` means the shape did not
   * support one, and the result table below it is the honest rendering.
   */
  chart?: ChartSpec;
  check?: { verdict: AnalystCheckVerdict; note: string };
  error?: string;
  /** The user edited this step's SQL and re-ran it (shown, and it matters). */
  edited?: boolean;
  /**
   * The governed query this step asked for, when the planner could express it
   * against a semantic model. Present means the SQL below was COMPILED from
   * the model's own definitions rather than written by the model.
   *
   * Until now governance was advisory: the definitions went into the prompt
   * with "never improvise a different formula" attached, and nothing checked
   * whether the SQL that came back obeyed. A metric that is authoritative
   * only when the model feels like it is not a governed metric.
   */
  semantic?: SemanticQuery;
  /** What the compile actually did — the disclosure half of `semantic`. */
  governed?: {
    model: string;
    /** A declared rollup answered instead of the fact table. Say which. */
    rollup?: string;
    /** Row filters / column masks the server applied for this viewer. */
    accessNote?: string;
  };
  /**
   * A what-if run of this step under changed assumptions.
   *
   * Kept BESIDE the measured result rather than replacing it, and never fed
   * into the findings: the write-up describes what was measured, and a
   * scenario that quietly joins it becomes a number nobody can tell from one.
   */
  scenario?: {
    changes: ScenarioChange[];
    label: string;
    sql: string;
    columns: string[];
    rows: Record<string, unknown>[];
    delta: MetricDelta[];
  };
  status: "pending" | "writing_sql" | "running" | "checking" | "done" | "error";
};

/**
 * The governed fields a plan is allowed to name, flattened for validation.
 *
 * Kept as plain names rather than the full SemanticModel because the analyst
 * only needs to answer one question here — "does this model really have a
 * metric called that?" — and the full model lives on the server, which is
 * where the SQL is actually compiled.
 */
export type GovernedModelFields = {
  name: string;
  label?: string;
  table: string;
  metrics: string[];
  dimensions: string[];
  timeDimensions: string[];
  /** Declared assumptions a what-if scenario may vary. */
  parameters?: ScenarioParameter[];
};

export type AnalystTurn = {
  question: string;
  /** The analyst's stated approach — shown before any query runs. */
  approach?: string;
  steps: AnalystStep[];
  /** Final synthesis, markdown. */
  answer?: string;
  /** The LEAD visual's step — the one that best answers the question. */
  chartStep?: number;
  /** Questions this analysis makes worth asking next. */
  followUps?: string[];
  /**
   * The analyst stopped BEFORE querying to ask something it could not
   * sensibly decide. The assumption is what it would proceed with, so the
   * user can accept it in one click instead of retyping the question.
   */
  clarify?: string;
  assumption?: string;
  /**
   * The findings predate the step results below them, because a step was
   * edited and re-run after they were written. Shown as a warning until the
   * user rewrites them — silently keeping stale prose next to fresh numbers
   * is the exact dishonesty this feature exists to avoid.
   */
  answerStale?: boolean;
  /**
   * A human's verdict on this analysis, pinned to the steps it was given.
   *
   * See analystVerification: the fingerprint is what stops a green tick
   * outliving the SQL it vouched for. An unverified answer is read with
   * ordinary caution; a falsely verified one is read with none.
   */
  verification?: TurnVerification;
  status: "planning" | "working" | "checking" | "synthesizing" | "done" | "clarifying" | "error";
  error?: string;
  at?: string;
  /**
   * The model that produced THIS turn, stamped when it ran.
   *
   * An analyst's model can be changed after the fact, and without this the
   * report header reads the analyst's CURRENT model and attributes every
   * older analysis to a model that never saw the question. Absent on turns
   * recorded before analysts were editable — those necessarily ran on the
   * analyst's model of the day, so falling back to it is accurate for them
   * and only for them.
   */
  model?: string;
};

/**
 * What to print as the model behind a set of turns.
 *
 * Several models can appear in one thread once the analyst is edited
 * mid-conversation, and naming just one of them would be a guess. Turns
 * with no stamp fall back to `current` — see AnalystTurn.model for why that
 * is sound for exactly those turns.
 */
/**
 * What an analyst should be called after its data source changes.
 *
 * A name the user typed is theirs and survives. A name they never touched is
 * one WE derived from the old source, so leaving it alone would let an
 * analyst go on describing data it no longer reads — "Snowflake · sales"
 * pointing at a local upload. Compared against the auto-name of the OLD
 * source, which is the only way to tell the two cases apart after the fact.
 */
export function analystNameOnEdit(args: {
  currentName: string;
  autoNameForOldSource: string;
  autoNameForNewSource: string;
}): string {
  return args.currentName.trim() === args.autoNameForOldSource.trim()
    ? args.autoNameForNewSource
    : args.currentName;
}

export function modelsUsedIn(turns: AnalystTurn[], current: string): string {
  const names = new Set<string>();
  for (const t of turns ?? []) names.add((t.model ?? current).split("::").pop() ?? current);
  const list = [...names].filter(Boolean);
  if (list.length === 0) return current.split("::").pop() ?? current;
  if (list.length <= 2) return list.join(" + ");
  return `${list[0]} + ${list.length - 1} more`;
}

// ── Limits ───────────────────────────────────────────────────────────────

/** Most questions decompose into 2–3 queries; more is a sign of drift. */
export const MAX_ANALYSIS_STEPS = 4;

/** Rows kept per step in the stored trace (same discipline as widgets). */
export const ANALYST_ROW_CAP = 50;

/** Prior Q/A pairs carried into the next question's context. */
export const ANALYST_MEMORY_TURNS = 4;

/** Follow-up questions offered after an answer. Three fit; six is a menu. */
export const MAX_FOLLOW_UPS = 3;

/**
 * Completion budgets, sized for REASONING models — which is what this
 * feature tells you to pick.
 *
 * A reasoning model's thinking tokens are charged against the completion
 * cap, so a budget sized for the visible answer starves the invisible part
 * and the model returns nothing at all. Measured: gpt-5-mini, planning a
 * three-part discount question with a 1,200 cap, spent 1,152 completion
 * tokens and returned `{}` — 25 seconds, real money, and a user-facing
 * "returned no analysis steps". These are deliberately generous; the plan
 * and check replies are small, so the headroom is spent on thinking, not on
 * output nobody reads.
 */
export const ANALYST_TOKENS = { plan: 6000, check: 8000, synthesis: 8000 } as const;

// ── Reasoning-model heuristic (the create dialog's nudge) ────────────────

// Families marketed and benchmarked as reasoning/thinking models. The
// dialog SUGGESTS one of these; it never blocks — the list is a heuristic
// over provider ids, not a gate, and new model names appear monthly.
const REASONING_MODEL_RE =
  /(^|[/:.-])o[134](\b|-)|gpt-5|deepseek-r1|\bqwq\b|thinking|reasoner|reasoning|claude-(fable|mythos|opus)|(opus|sonnet)-[45]|claude-[45]|gemini-[23][.-]5-pro|grok-[34]/i;

export function isReasoningModelId(id: string): boolean {
  return REASONING_MODEL_RE.test(id);
}

// ── Pure helpers ─────────────────────────────────────────────────────────

/** SELECT/WITH only, one statement — applied to every SQL before it runs. */
export function assertSelectOnly(sql: string): string {
  const s = sql.trim().replace(/;\s*$/, "");
  if (!/^(select|with)\b/i.test(s)) {
    throw new Error("The analyst may only run SELECT statements.");
  }
  if (s.includes(";")) {
    throw new Error("The analyst may only run a single statement.");
  }
  return s;
}

/** Cap a step's stored rows; everything else in the trace is kept. */
export function trimStepForStorage(step: AnalystStep): AnalystStep {
  if (!step.rows || step.rows.length <= ANALYST_ROW_CAP) return step;
  return { ...step, rows: step.rows.slice(0, ANALYST_ROW_CAP) };
}

export function trimTurnForStorage(turn: AnalystTurn): AnalystTurn {
  return { ...turn, steps: turn.steps.map(trimStepForStorage) };
}

/**
 * A turn as an ANONYMOUS embed visitor may receive it.
 *
 * The signed-in screen shows each step's SQL because the reader owns the data
 * and re-running it is the point. On a public embed that same field publishes
 * internal table and column names — `FROM hr_dept_monthly` names a table
 * nobody outside the company should learn from a chat widget. This is the
 * same reason sanitizePublicWidgets allow-lists render fields for embedded
 * dashboards, and it is enforced HERE rather than by the page declining to
 * render it: a field that reaches the browser has been published, whatever
 * the UI does with it.
 *
 * `governed` survives deliberately. It names the semantic model the step
 * compiled against, which the owner chose to define and which is the reader's
 * evidence that a number came from a governed definition rather than
 * improvised SQL — a trust signal, not a schema leak.
 */
export function sanitizePublicTurn(turn: AnalystTurn): AnalystTurn {
  return {
    ...turn,
    steps: turn.steps.map((s) => {
      const { sql: _sql, semantic: _semantic, ...safe } = s;
      return safe;
    }),
  };
}

/** Compact Q→A lines from prior turns, for conversational continuity. */
export function priorContext(turns: AnalystTurn[], max = ANALYST_MEMORY_TURNS): string {
  const done = turns.filter((t) => t.status === "done" && t.answer);
  const recent = done.slice(-max);
  if (recent.length === 0) return "";
  const lines = recent.map(
    (t) => `Q: ${t.question}\nA: ${(t.answer ?? "").slice(0, 500).replace(/\s+/g, " ")}`,
  );
  return `EARLIER IN THIS ANALYSIS:\n${lines.join("\n")}\n`;
}

// ── Prompts (pure, exported so tests read what the app actually sends) ───

/**
 * The governed vocabulary, written out so the plan can NAME it exactly.
 *
 * `describeSchema` already shows governed metrics as expressions, which tells
 * the model what they mean. This tells it what they are CALLED, which is the
 * part it has to get exactly right for the compiler to accept the block.
 */
export function describeGovernedVocabulary(catalog: GovernedModelFields[]): string {
  if (catalog.length === 0) return "";
  const lines = catalog.slice(0, 8).map((m) => {
    const met = m.metrics.slice(0, 24).join(", ");
    const dim = m.dimensions.slice(0, 24).join(", ");
    const time = m.timeDimensions.length
      ? `\n  time dimensions: ${m.timeDimensions.join(", ")}`
      : "";
    return `MODEL ${m.name}${m.label ? ` (${m.label})` : ""} over ${m.table}\n  metrics: ${met}\n  dimensions: ${dim}${time}`;
  });
  return (
    "\n\nGOVERNED MODELS YOU CAN COMPILE AGAINST (preferred — these definitions are " +
    "authoritative and the SQL is generated from them, not by you):\n" +
    lines.join("\n")
  );
}

export function buildAnalysisPlanPrompt(args: {
  schema: string;
  question: string;
  prior: string;
  /** Governed models in scope; empty means the plan cannot claim governance. */
  catalog?: GovernedModelFields[];
}): { systemPrompt: string; userPrompt: string } {
  const vocabulary = describeGovernedVocabulary(args.catalog ?? []);
  const governedRule = vocabulary
    ? "\n\nPREFER A GOVERNED STEP when the step's numbers come from a governed model's " +
      'metrics. Add "semantic": { "model": "<model name>", "metrics": ["<metric>"], ' +
      '"dimensions": ["<dimension>"], "grains": { "<time dimension>": "month" }, ' +
      '"filters": [{ "field": "<field>", "op": "=", "value": "..." }], ' +
      '"orderBy": [{ "field": "<metric or dimension>", "dir": "desc" }], "limit": 100 } ' +
      "to that step. ALWAYS give orderBy when the step asks for a top/bottom N — a limit " +
      "without an ordering returns arbitrary rows. " +
      "Use the EXACT names listed — every name is checked against the model, " +
      "and a step naming anything else silently loses its governed status and falls back to " +
      "hand-written SQL. Omit `semantic` for steps a governed model cannot express."
    : "";
  return {
    systemPrompt:
      "You are a senior data analyst planning an analysis. Decompose the question into the " +
      `SMALLEST set of concrete SQL-answerable steps (1-${MAX_ANALYSIS_STEPS}) over the ` +
      "provided schema. Each step is one query's worth of work with a measurable goal — " +
      '"total sales by region", not "explore the data". Prefer ONE step when one query ' +
      "answers the question; add steps only when the answer genuinely needs several angles " +
      "(a total plus a breakdown, a trend plus its outliers, a comparison of two segments). " +
      "Only use tables and columns that exist in the schema. Do not write SQL here.\n\n" +
      // A guess that runs is worse than a question that doesn't: a wrong
      // assumption comes back as confident numbers nobody can see the
      // assumption behind. Measured: "…this quarter" ran against a quarter
      // with no rows and reported an empty breakdown as the answer.
      "ASK BEFORE GUESSING, but only when the question cannot be answered WELL without an " +
      'answer: an unstated time range on a time-sensitive question, a word ("churn", "active") ' +
      "the schema defines two plausible ways, or a metric the schema does not have under any " +
      "name. Do NOT ask about things you can decide sensibly yourself — sort order, chart type, " +
      "row limits, which of two equivalent columns to group by. When you must ask, return " +
      '{ "clarify": "one specific question", "assumption": "what you would assume if told to ' +
      'proceed" } and NOTHING else.' +
      governedRule,
    userPrompt:
      `${args.schema}${vocabulary}\n\n${args.prior}QUESTION: ${args.question}\n\n` +
      `Return JSON: { "approach": "1-3 sentences on how you'll answer and why these steps", ` +
      `"steps": [ { "goal": "concrete, measurable step goal"${
        vocabulary ? ', "semantic": { ... } (optional)' : ""
      } } ] } ` +
      `— OR { "clarify": "...", "assumption": "..." } if you genuinely cannot proceed well.`,
  };
}

export function buildCheckPrompt(args: {
  question: string;
  steps: Array<{ goal: string; sql?: string; facts: string; error?: string }>;
  /** Governed models in scope — named so the reviewer cannot mistake one for a table. */
  catalog?: GovernedModelFields[];
}): { systemPrompt: string; userPrompt: string } {
  // A step that FELL BACK to hand-written SQL still carries a goal phrased
  // around the governed model ("From saas_sales_model, compute total_sales…").
  // Measured live: the reviewer read that as a table name, "corrected" correct
  // SQL to `FROM saas_sales_model`, and the rewrite died on
  // `Catalog Error: Table with name saas_sales_model does not exist!`. The
  // original result survived and the step was flagged, so nothing wrong was
  // shown — but the concern raised was fictional, and a reviewer that cries
  // wolf is a reviewer people stop reading.
  const modelsAreNotTables = (args.catalog ?? []).length
    ? "\n\nGOVERNED MODELS ARE NOT TABLES. " +
      (args.catalog ?? [])
        .map((m) => `"${m.name}" is a semantic model over the table ${m.table}`)
        .join("; ") +
      ". A step's goal may name a model; the SQL must still select FROM the underlying " +
      "table. Never rewrite a query to select from a model name."
    : "";
  const stepBlocks = args.steps
    .map(
      (s, i) =>
        `STEP ${i + 1}: ${s.goal}\nSQL: ${s.sql ?? "(none)"}\n` +
        (s.error ? `ENGINE ERROR: ${s.error}` : `RESULT FACTS: ${s.facts}`),
    )
    .join("\n\n");
  return {
    systemPrompt:
      "You are the same analyst REVIEWING YOUR OWN WORK before presenting it. For each step, " +
      "judge whether its result actually answers its goal: empty results for questions that " +
      "should have data, totals of the wrong magnitude, groupings split by case variants, a " +
      "LIMIT that cut a ranking short, nulls sorted to the top, the wrong column. " +
      'Verdicts: "pass" (result answers the goal), "suspect" (present the result but flag ' +
      'the concern in the note). If a step is WRONG and you can fix it, return "refined_sql" ' +
      "with a corrected single SELECT statement — it will be re-executed and replace the " +
      "result. Be specific in notes: name the number or shape that concerns you. Never " +
      "invent data." +
      modelsAreNotTables,
    userPrompt:
      `QUESTION: ${args.question}\n\n${stepBlocks}\n\n` +
      `Return JSON: { "checks": [ { "verdict": "pass|suspect", "note": "one sentence", ` +
      `"refined_sql": "SELECT ... (only when correcting)" } ], ` +
      `"headline": <index of the step whose result best answers the question, 0-based> }`,
  };
}

export function buildSynthesisPrompt(args: {
  question: string;
  approach: string;
  prior: string;
  steps: Array<{ goal: string; facts: string; verdict?: string; note?: string; error?: string }>;
}): { systemPrompt: string; userPrompt: string } {
  const stepBlocks = args.steps
    .map(
      (s, i) =>
        `STEP ${i + 1}: ${s.goal}\n` +
        (s.error
          ? `FAILED: ${s.error}`
          : `RESULT: ${s.facts}${s.verdict ? `\nCHECK: ${s.verdict}${s.note ? ` — ${s.note}` : ""}` : ""}`),
    )
    .join("\n\n");
  return {
    systemPrompt:
      "You are a senior data analyst writing up findings. Answer the question using ONLY the " +
      "step results below — every number in your answer must appear in a step result, cited " +
      "like (step 2). Lead with the direct answer, then the supporting evidence, then any " +
      "caveat a careful analyst would add (suspect checks, failed steps, sample caps). " +
      "Markdown, short paragraphs and lists, no headings. If the steps do not answer the " +
      "question, say exactly what is missing instead of guessing.",
    userPrompt:
      `${args.prior}QUESTION: ${args.question}\nAPPROACH: ${args.approach}\n\n${stepBlocks}\n\n` +
      `Return JSON: { "answer": "markdown", "follow_ups": ` +
      `["up to ${MAX_FOLLOW_UPS} short questions THIS analysis makes worth asking next — ` +
      `each answerable from the same data, each a real next step rather than a restatement"] }`,
  };
}

// ── Parsers (validated, exported) ────────────────────────────────────────

const GRAINS: readonly TimeGrain[] = [
  "day",
  "week",
  "month",
  "quarter",
  "year",
  "fiscal_quarter",
  "fiscal_year",
] as const;

/**
 * Turn a plan's governed block into a SemanticQuery, or return null.
 *
 * EVERY NAME IS CHECKED against the catalog the analyst actually loaded. A
 * metric the model invented does not become a governed metric by being
 * named in a JSON field called "metrics" — and the failure mode of letting
 * it through is the worst kind: the step would carry a "Governed" badge over
 * SQL that compiles from something nobody signed off, or fail on the server
 * with an error the reader cannot connect to the claim.
 *
 * Returning null is not a refusal to answer. The caller falls back to
 * model-written SQL and the step is shown as ungoverned, which is the honest
 * description of what happened.
 */
export function parseSemanticStep(
  raw: unknown,
  catalog: GovernedModelFields[],
): SemanticQuery | null {
  const o = (raw ?? {}) as Record<string, unknown>;
  const modelName = typeof o.model === "string" ? o.model.trim() : "";
  if (!modelName) return null;
  const model = catalog.find((m) => m.name.toLowerCase() === modelName.toLowerCase());
  if (!model) return null;

  const pick = (v: unknown, allowed: string[]): string[] => {
    const want = Array.isArray(v) ? v : typeof v === "string" ? [v] : [];
    const out: string[] = [];
    for (const item of want) {
      if (typeof item !== "string") continue;
      const hit = allowed.find((a) => a.toLowerCase() === item.trim().toLowerCase());
      if (hit && !out.includes(hit)) out.push(hit);
    }
    return out;
  };

  const metrics = pick(o.metrics, model.metrics);
  const dimensions = pick(o.dimensions, model.dimensions);
  // A governed query with no metric is not a governed query — it is a column
  // listing that would be better served by ordinary SQL.
  if (metrics.length === 0) return null;
  // Any name the plan asked for that the model does not have means the plan
  // was reasoning about a schema that does not exist. Compiling the subset
  // that happened to match would answer a DIFFERENT question, silently.
  const askedMetrics = Array.isArray(o.metrics) ? o.metrics.length : o.metrics ? 1 : 0;
  const askedDims = Array.isArray(o.dimensions) ? o.dimensions.length : o.dimensions ? 1 : 0;
  if (metrics.length !== askedMetrics || dimensions.length !== askedDims) return null;

  const q: SemanticQuery = { model: model.name, metrics };
  if (dimensions.length) q.dimensions = dimensions;

  // Grains: only on dimensions this query actually selected, and only the
  // grains the compiler knows.
  if (o.grains && typeof o.grains === "object") {
    const grains: Record<string, TimeGrain> = {};
    for (const [k, v] of Object.entries(o.grains as Record<string, unknown>)) {
      const dim = dimensions.find((d) => d.toLowerCase() === k.trim().toLowerCase());
      const grain = GRAINS.find((g) => g === String(v).trim().toLowerCase());
      if (dim && grain) grains[dim] = grain;
    }
    if (Object.keys(grains).length) q.grains = grains;
  }

  // Filters reference fields by name too, so they get the same treatment:
  // a filter on a field the model does not have is dropped along with the
  // whole block rather than quietly widening the result.
  if (Array.isArray(o.filters) && o.filters.length) {
    const fields = [...model.metrics, ...model.dimensions];
    const filters: SemanticFilter[] = [];
    for (const f of o.filters as unknown[]) {
      const fo = (f ?? {}) as Record<string, unknown>;
      const field = fields.find(
        (a) =>
          a.toLowerCase() ===
          String(fo.field ?? "")
            .trim()
            .toLowerCase(),
      );
      const op = typeof fo.op === "string" ? fo.op.trim() : "";
      if (!field || !op) return null;
      filters.push({ field, op, value: fo.value } as SemanticFilter);
    }
    if (filters.length) q.filters = filters;
  }

  // ORDER BY, because "top 5" without it is five arbitrary rows.
  //
  // Measured live: a governed "the 5 orders with the largest discount"
  // compiled to a LIMIT with no ordering and returned discounts of 0, 0.65,
  // 0.2… The self-check spotted it and rewrote the SQL by hand, which
  // rescued the answer at the cost of the step's compiled status. Supporting
  // it here keeps the query governed AND correct.
  if (Array.isArray(o.orderBy) && o.orderBy.length) {
    const selectable = [...metrics, ...dimensions];
    const orderBy: NonNullable<SemanticQuery["orderBy"]> = [];
    for (const raw of o.orderBy as unknown[]) {
      const ob = (raw ?? {}) as Record<string, unknown>;
      const name = typeof ob === "string" ? ob : String(ob.field ?? "");
      const field = selectable.find((f) => f.toLowerCase() === name.trim().toLowerCase());
      // Ordering by something the query does not select is not a tidier
      // result, it is a different one — refuse the block as with filters.
      if (!field) return null;
      orderBy.push({
        field,
        dir: String(ob.dir ?? "desc").toLowerCase() === "asc" ? "asc" : "desc",
      });
    }
    if (orderBy.length) q.orderBy = orderBy;
  }

  if (typeof o.limit === "number" && Number.isFinite(o.limit) && o.limit > 0) {
    q.limit = Math.min(Math.trunc(o.limit), ANALYST_ROW_CAP * 20);
  }
  return q;
}

export function parseAnalysisPlan(
  raw: unknown,
  /** Governed models in scope. Omitted → no step can claim to be governed. */
  catalog: GovernedModelFields[] = [],
): {
  approach: string;
  steps: { goal: string; semantic?: SemanticQuery }[];
  /** Set INSTEAD of steps when the analyst needs an answer before it can plan. */
  clarify?: string;
  /** What it would assume if told to proceed anyway. */
  assumption?: string;
} {
  // Tolerant by measurement, like parseSynthesis: models in JSON mode wrap
  // the plan, name the goal key differently, or return plain strings.
  const root = (raw ?? {}) as Record<string, unknown>;
  const o = (root.plan && typeof root.plan === "object" ? root.plan : root) as Record<
    string,
    unknown
  >;
  const approach = typeof o.approach === "string" ? o.approach.trim() : "";
  const list = Array.isArray(o.steps)
    ? o.steps
    : Array.isArray(o.analysis_steps)
      ? o.analysis_steps
      : ((Object.values(o).find(Array.isArray) as unknown[] | undefined) ?? []);
  const goalOf = (s: unknown): string => {
    if (typeof s === "string") return s.trim();
    const obj = (s ?? {}) as Record<string, unknown>;
    for (const k of ["goal", "step", "description", "title", "objective", "name"]) {
      if (typeof obj[k] === "string" && (obj[k] as string).trim()) return (obj[k] as string).trim();
    }
    return "";
  };
  const steps = list
    .map((s) => {
      const goal = goalOf(s);
      const obj = (s ?? {}) as Record<string, unknown>;
      const semantic = parseSemanticStep(obj.semantic ?? obj.governed, catalog);
      return semantic ? { goal, semantic } : { goal };
    })
    .filter((s) => s.goal.length > 0)
    .slice(0, MAX_ANALYSIS_STEPS);
  // A clarification is only honoured when the model ALSO produced no plan.
  // Both together means it hedged: it knew how to proceed and asked anyway,
  // and stopping there would make the feature a nag.
  const clarify = typeof o.clarify === "string" ? o.clarify.trim() : "";
  if (steps.length === 0 && clarify) {
    return {
      approach: "",
      steps: [],
      clarify,
      assumption: typeof o.assumption === "string" ? o.assumption.trim() : "",
    };
  }
  if (steps.length === 0) {
    // An EMPTY reply and a badly-shaped one are different failures, and the
    // empty one has a specific cause worth naming: a reasoning model that
    // spent its whole completion budget thinking. Saying "try rephrasing"
    // for that sends the user to fix the one thing that was fine.
    if (Object.keys(root).length === 0) {
      throw new Error(
        "The model returned an empty plan — it likely spent its completion budget on reasoning. " +
          "Try a question with fewer parts, or an analyst on a model with more headroom.",
      );
    }
    throw new Error("The analyst returned no analysis steps — try rephrasing the question.");
  }
  return { approach, steps };
}

/**
 * The synthesis reply, tolerantly. Models in JSON mode legitimately return a
 * bare JSON string (JSON.parse('"text"') succeeds), or wrap the markdown
 * under a key other than "answer" — measured live with gpt-5-mini, whose
 * write-up came back shaped so the strict `.answer` read produced the
 * "no write-up" fallback on a perfectly good analysis.
 */
export function parseSynthesis(raw: unknown): string {
  if (typeof raw === "string") return raw.trim();
  const o = (raw ?? {}) as Record<string, unknown>;
  for (const k of ["answer", "markdown", "text", "findings", "summary"]) {
    if (typeof o[k] === "string" && (o[k] as string).trim()) return (o[k] as string).trim();
  }
  // A single string value under an unexpected key is still the answer.
  const strings = Object.values(o).filter(
    (v): v is string => typeof v === "string" && v.trim().length > 0,
  );
  return strings.length === 1 ? strings[0].trim() : "";
}

/**
 * The synthesis reply: the write-up AND the questions it makes worth asking
 * next. Follow-ups are optional — an analysis with none is still complete,
 * so a missing or malformed list never costs the user their answer.
 */
export function parseSynthesisReply(raw: unknown): { answer: string; followUps: string[] } {
  const answer = parseSynthesis(raw);
  const o = (raw ?? {}) as Record<string, unknown>;
  const list = ["follow_ups", "followUps", "next_questions", "suggestions"]
    .map((k) => o[k])
    .find(Array.isArray) as unknown[] | undefined;
  const followUps = (list ?? [])
    .map((q) => (typeof q === "string" ? q.trim() : ""))
    .filter((q) => q.length > 0 && q.length <= 160)
    .slice(0, MAX_FOLLOW_UPS);
  return { answer, followUps };
}

export function parseCheckResponse(
  raw: unknown,
  stepCount: number,
): {
  checks: Array<{ verdict: "pass" | "suspect"; note: string; refined_sql?: string }>;
  headline: number;
} {
  const o = (raw ?? {}) as { checks?: unknown; headline?: unknown };
  const list = Array.isArray(o.checks) ? o.checks : [];
  const checks = Array.from({ length: stepCount }, (_, i) => {
    const c = (list[i] ?? {}) as { verdict?: unknown; note?: unknown; refined_sql?: unknown };
    const verdict = c.verdict === "suspect" ? ("suspect" as const) : ("pass" as const);
    const note = typeof c.note === "string" ? c.note.trim() : "";
    const refined =
      typeof c.refined_sql === "string" && c.refined_sql.trim().length > 0
        ? c.refined_sql.trim()
        : undefined;
    return { verdict, note, ...(refined ? { refined_sql: refined } : {}) };
  });
  const h = typeof o.headline === "number" ? Math.trunc(o.headline) : 0;
  const headline = h >= 0 && h < stepCount ? h : 0;
  return { checks, headline };
}

/** Rows small enough to hand the model verbatim rather than summarised. */
export const QUOTE_ROWS_UP_TO = 12;

/**
 * When a step's result compares two periods by dimension, decompose it.
 *
 * "Why did it move" is the question every BI tool gets asked and few
 * answer. The model already writes SQL that fetches both periods side by
 * side; recognising that shape and doing the CONTRIBUTION ARITHMETIC here
 * turns it into an answer — computed, ranked and reproducible, rather than
 * a paragraph of plausible attributions. Returns null whenever the shape is
 * anything else, and the ordinary path continues untouched.
 */
export function driversForStep(step: {
  columns?: string[];
  rows?: Record<string, unknown>[];
}): DriverAnalysis | null {
  if (!step.columns || !step.rows) return null;
  const inputs = driverInputsFrom(step.columns, step.rows);
  if (!inputs || inputs.length === 0) return null;
  const analysis = analyseDrivers(inputs);
  // Two periods that are identical everywhere are not a change story, and
  // labelling them one would invent significance the data does not have.
  if (analysis.contributions.every((c) => c.change === 0)) return null;
  return analysis;
}

/**
 * What the check and the write-up are TOLD a step returned.
 *
 * describeResultFacts summarises — total, max, min, row count — which is
 * right for a thousand rows and actively harmful for three. Fed only
 * summaries, the model wrote "the per-segment totals are missing" while the
 * three per-segment totals sat in the table directly above it, and hedged
 * the same way on every small result. Measured on two live runs before
 * anyone noticed the write-up was under-reporting its own evidence.
 *
 * So: quote small results in full, summarise big ones, and say which.
 */
export function describeStepResult(result: QueryResult, maxRows = QUOTE_ROWS_UP_TO): string {
  // Two shapes get arithmetic attached before the model ever sees them, so
  // the write-up cites computed values instead of eyeballing columns: a
  // two-period breakdown gets contribution analysis, and a time series gets
  // its trend, outliers and (only when the history supports one) a labelled
  // projection.
  const drivers = driversForStep({ columns: result.columns, rows: result.rows });
  const driverBlock = drivers ? `\n\nCONTRIBUTION ANALYSIS:\n${describeDrivers(drivers)}` : "";
  const series = seriesFrom(result.columns, result.rows);
  const reading = series ? readSeries(series) : null;
  const seriesBlock = reading ? `\n\n${describeSeries(reading, forecastSeries(series!))}` : "";
  const extra = driverBlock + seriesBlock;
  if (result.rows.length === 0 || result.rows.length > maxRows) {
    return describeResultFacts(result) + extra;
  }
  const cell = (v: unknown) => {
    if (v === null || v === undefined) return "null";
    const s = typeof v === "number" ? String(Number(v.toFixed(4))) : String(v);
    return s.length > 60 ? `${s.slice(0, 57)}…` : s;
  };
  const rows = result.rows
    .map((r) => result.columns.map((c) => `${c}=${cell(r[c])}`).join(" | "))
    .join("\n");
  return (
    `${result.rows.length} row${result.rows.length === 1 ? "" : "s"}, ` +
    `columns: ${result.columns.join(", ")}\n${rows}${extra}`
  );
}

/**
 * Does this result have a shape worth drawing?
 *
 * Cheap and honest, and it runs BEFORE any LLM call: a step with no rows,
 * or with nothing but labels, has nothing to plot, and asking a model to
 * chart it wastes a call to be told "table". Everything else is offered to
 * suggestChart, which makes the actual choice.
 */
export function isChartableShape(result: {
  columns: string[];
  rows: Record<string, unknown>[];
}): boolean {
  if (result.rows.length === 0) return false;
  const numeric = result.columns.filter((c) =>
    result.rows.some((r) => typeof r[c] === "number" && Number.isFinite(r[c] as number)),
  );
  if (numeric.length === 0) return false;
  // One row and one number is a KPI; anything more needs a category to plot
  // against, which is any non-numeric column.
  if (result.rows.length === 1) return result.columns.length <= 3;
  return numeric.length > 0 && result.columns.length >= 2;
}

/**
 * Which step's visual leads the answer.
 *
 * The self-check nominates a headline; it only counts if that step actually
 * produced a chart. Otherwise the first step that did leads, and if none
 * did the turn simply has no lead visual.
 */
export function leadChartStep(steps: AnalystStep[], headline: number): number | undefined {
  const drawable = (i: number) => steps[i]?.chart && steps[i].chart.type !== "table";
  if (drawable(headline)) return headline;
  const first = steps.findIndex((_, i) => drawable(i));
  return first >= 0 ? first : undefined;
}

/**
 * Suggest a chart for EVERY chartable step, concurrently.
 *
 * Exported with an injectable suggester so a test can prove that all of
 * them get one — the version that charted only the headline is exactly the
 * regression this guards, and it is invisible to a test of the pure
 * helpers alone.
 */
export async function chartEveryStep(args: {
  turn: AnalystTurn;
  results: (QueryResult | null)[];
  question: string;
  model?: string;
  /** Model transport for the default suggester; see LlmJsonFn. */
  llm?: LlmJsonFn;
  suggest?: (a: {
    question: string;
    result: QueryResult;
    plan: BiPlan;
    model?: string;
    llm?: LlmJsonFn;
  }) => Promise<ChartSpec>;
}): Promise<void> {
  const suggest = args.suggest ?? suggestChart;
  await Promise.all(
    args.turn.steps.map(async (step, i) => {
      const res = args.results[i];
      if (!res || !isChartableShape(res)) return;
      try {
        step.chart = await suggest({
          // The STEP's goal, not the whole question: the chart has to fit
          // what this query returned, and the overall question describes
          // something wider than any single step.
          question: step.goal,
          result: res,
          plan: { intent: step.goal, tables: [], metrics: [], breakdowns: [] },
          model: args.model,
          llm: args.llm,
        });
      } catch {
        /* a chart is a nice-to-have; the result table still stands */
      }
    }),
  );
}

// ── The loop ─────────────────────────────────────────────────────────────

export async function runAnalystTurn(args: {
  question: string;
  datasets: DatasetMeta[];
  semantics: Map<string, SemanticEntry>;
  metrics: SavedMetric[];
  /** Prior turns of THIS thread, for conversational continuity. */
  priorTurns: AnalystTurn[];
  /** Encoded "provider::model" choice — the analyst's pinned model. */
  model?: string;
  /** Override SQL execution (warehouse scope); omitted = local DuckDB. */
  execute?: (sql: string) => Promise<QueryResult>;
  /** Human name of the engine when `execute` is provided. */
  dialect?: string;
  /** Governed models the plan may compile against. Empty = none, and no
   *  step can be marked governed. */
  catalog?: GovernedModelFields[];
  /**
   * Run a compiled semantic query. Injected rather than imported so the loop
   * stays testable and so compilation keeps happening SERVER-side, where the
   * full model, its row filters and its column masks live — the browser only
   * ever holds field names.
   */
  runSemantic?: (q: SemanticQuery) => Promise<{
    sql: string;
    columns: string[];
    rows: Record<string, unknown>[];
    rollup?: string;
    access_note?: string;
  }>;
  /**
   * How to reach the model. Defaults to the browser session, which is the
   * only thing an EMBED does not have — a public embed runs this same loop
   * with a server-side transport authenticating as the analyst's owner, so
   * the reasoning an anonymous visitor gets is the reasoning the owner gets.
   */
  llm?: LlmJsonFn;
  onUpdate: (turn: AnalystTurn) => void;
}): Promise<AnalystTurn> {
  const ask: LlmJsonFn = args.llm ?? llmJson;
  const turn: AnalystTurn = {
    question: args.question,
    steps: [],
    status: "planning",
    at: new Date().toISOString(),
    // Stamped HERE, not read from the analyst at render time: the analyst's
    // model is editable, and a turn must keep saying which model actually
    // answered it.
    model: args.model,
  };
  const emit = () => args.onUpdate({ ...turn, steps: turn.steps.map((s) => ({ ...s })) });
  emit();

  // De-duplicates identical SQL WITHIN this turn only. Same query, same
  // instant, so the shared result needs no disclosure — and it is discarded
  // when the turn ends, because between two questions the data can move.
  const queryCache = createTurnCache<QueryResult>();
  const sourceKey = args.execute ? `wh:${args.dialect ?? "warehouse"}` : "local";
  const runSql = async (sql: string): Promise<QueryResult> => {
    const clean = assertSelectOnly(sql);
    return queryCache.run(resultCacheKey(sourceKey, clean), async () =>
      args.execute
        ? await args.execute(clean)
        : await (await import("@/lib/sqlEngine")).runQuery(clean),
    );
  };
  const captureResult = (step: AnalystStep, res: QueryResult) => {
    step.columns = res.columns;
    step.rowCount = res.rows.length;
    step.rows = res.rows.slice(0, ANALYST_ROW_CAP);
  };
  // Facts are described from the FULL result, then the step keeps a capped
  // sample — the check must see true magnitudes, the store must stay small.
  const results: (QueryResult | null)[] = [];

  try {
    // 1. PLAN
    await ensureGovernedCatalog();
    const schema = describeSchema(args.datasets, args.semantics, args.metrics);
    const prior = priorContext(args.priorTurns);
    const catalog = args.catalog ?? [];
    const planPrompt = buildAnalysisPlanPrompt({
      schema,
      question: args.question,
      prior,
      catalog,
    });
    const plan = parseAnalysisPlan(
      await ask<unknown>({ ...planPrompt, model: args.model, maxTokens: ANALYST_TOKENS.plan }),
      catalog,
    );
    // 1b. STOP AND ASK, when proceeding would mean inventing the question.
    // A guess that runs produces confident numbers with the assumption
    // buried in SQL nobody reads; a question costs one exchange and leaves
    // the analysis defensible. The assumption is offered alongside so the
    // usual answer is one click, not a retyped question.
    if (plan.clarify) {
      turn.clarify = plan.clarify;
      turn.assumption = plan.assumption;
      turn.status = "clarifying";
      emit();
      return turn;
    }
    turn.approach = plan.approach;
    turn.steps = plan.steps.map((s) => ({
      goal: s.goal,
      ...(s.semantic ? { semantic: s.semantic } : {}),
      status: "pending" as const,
    }));
    turn.status = "working";
    emit();

    // 2. QUERY each step, CONCURRENTLY.
    //
    // Safe because no step consumes another's output: each step's SQL is
    // written from its own goal, and `results` is read only after this block.
    // See lib/analystParallel — if a step ever comes to depend on an earlier
    // step's rows, this has to become sequential again, because parallelism
    // would not fail loudly, it would produce plausible numbers.
    //
    // The trace still reads top to bottom: steps keep their positions and each
    // renders its own status, so the reader sees them finish out of order
    // rather than seeing them reordered.
    await mapWithConcurrency(turn.steps, ANALYST_STEP_CONCURRENCY, async (step, i) => {
      step.status = "writing_sql";
      emit();
      const stepPlan: BiPlan = {
        intent: `One step of a larger analysis. Overall question: ${args.question}`,
        tables: [],
        metrics: [],
        breakdowns: [],
      };
      try {
        // A GOVERNED STEP DOES NOT ASK THE MODEL FOR SQL. The compiler turns
        // the model's own metric definitions into the query — including the
        // fan-out refusals, rollup routing and row filters that a hand-written
        // SELECT has no way to honour. If compiling fails, the step falls back
        // to written SQL and LOSES its governed marking rather than keeping a
        // badge it can no longer justify.
        let compiled = false;
        if (step.semantic && args.runSemantic) {
          try {
            const res = await args.runSemantic(step.semantic);
            step.sql = res.sql;
            step.governed = {
              model: step.semantic.model,
              rollup: res.rollup,
              accessNote: res.access_note,
            };
            step.status = "running";
            emit();
            const governedResult: QueryResult = {
              columns: res.columns,
              rows: res.rows,
              row_count: res.rows.length,
              total_matched: res.rows.length,
              capped: false,
              duration_ms: 0,
            };
            captureResult(step, governedResult);
            results[i] = governedResult;
            step.status = "done";
            emit();
            compiled = true;
          } catch (e) {
            // Say what was attempted. A governed step that silently becomes an
            // ungoverned one teaches people the badge means nothing.
            step.governed = undefined;
            delete step.semantic;
            step.check = {
              verdict: "suspect",
              note:
                `The governed model could not answer this step (${(e as Error).message}), ` +
                `so the SQL below was written by the analyst instead of compiled.`,
            };
          }
        }
        // `return` rather than `continue`: this is now a callback per step,
        // and returning ends THIS step, not the whole batch.
        if (compiled) {
          emit();
          return;
        }
        step.sql = await generateSql({
          question: step.goal,
          plan: stepPlan,
          datasets: args.datasets,
          semantics: args.semantics,
          metrics: args.metrics,
          dialect: args.dialect,
          localEngine: args.execute ? undefined : "duckdb",
          model: args.model,
          llm: ask,
        });
        step.status = "running";
        emit();
        let res: QueryResult;
        try {
          res = await runSql(step.sql);
        } catch (e) {
          // One repair pass with the engine's own error, like the BI analyst.
          step.sql = await generateSql({
            question: step.goal,
            plan: stepPlan,
            datasets: args.datasets,
            semantics: args.semantics,
            metrics: args.metrics,
            dialect: args.dialect,
            localEngine: args.execute ? undefined : "duckdb",
            model: args.model,
            llm: ask,
            repair: { sql: step.sql, error: (e as Error).message },
          });
          emit();
          res = await runSql(step.sql);
        }
        captureResult(step, res);
        results[i] = res;
        step.status = "done";
      } catch (e) {
        step.error = (e as Error).message;
        step.status = "error";
        results[i] = null;
      }
      emit();
    });
    if (turn.steps.every((s) => s.status === "error")) {
      throw new Error(`Every analysis step failed — last error: ${turn.steps.at(-1)?.error}`);
    }

    // 3. SELF-CHECK (one call across all steps; refined SQL re-executes)
    turn.status = "checking";
    turn.steps.forEach((s) => {
      if (s.status === "done") s.status = "checking";
    });
    emit();
    const checkPrompt = buildCheckPrompt({
      question: args.question,
      steps: turn.steps.map((s, i) => ({
        goal: s.goal,
        sql: s.sql,
        facts: results[i] ? describeStepResult(results[i]!) : "(no result)",
        error: s.error,
      })),
      catalog,
    });
    let headline = 0;
    try {
      const checked = parseCheckResponse(
        await ask<unknown>({
          ...checkPrompt,
          model: args.model,
          maxTokens: ANALYST_TOKENS.check,
        }),
        turn.steps.length,
      );
      headline = checked.headline;
      for (let i = 0; i < turn.steps.length; i++) {
        const step = turn.steps[i];
        const c = checked.checks[i];
        if (step.status === "error") continue;
        if (c.refined_sql) {
          try {
            const res = await runSql(c.refined_sql);
            step.sql = c.refined_sql;
            // A REFINED STEP IS NO LONGER COMPILED. The correction is SQL the
            // model wrote, replacing what the compiler produced, so the badge
            // would now vouch for a query the semantic layer never saw —
            // the same lie the edit path already refuses to tell. Measured
            // live: a governed "top 5" compiled without ORDER BY, the check
            // rewrote it correctly, and the step kept its governed marking.
            const wasGoverned = step.governed?.model;
            step.governed = undefined;
            delete step.semantic;
            captureResult(step, res);
            results[i] = res;
            step.check = {
              verdict: "refined",
              note:
                (c.note || "Corrected on self-review.") +
                (wasGoverned
                  ? ` The correction is hand-written SQL, so this step is no longer compiled from ${wasGoverned}.`
                  : ""),
            };
          } catch (e) {
            // The refinement itself failed — keep the original result and
            // surface the concern rather than losing a working answer.
            step.check = {
              verdict: "suspect",
              note: `${c.note || "Self-review proposed a correction"} (correction failed: ${(e as Error).message})`,
            };
          }
        } else {
          step.check = { verdict: c.verdict, note: c.note };
        }
        step.status = "done";
      }
    } catch {
      // A failed check call must not sink a finished analysis: present the
      // results unchecked and SAY so, never silently pretend they passed.
      turn.steps.forEach((s) => {
        if (s.status === "checking") {
          s.status = "done";
          s.check = { verdict: "suspect", note: "Self-check unavailable for this run." };
        }
      });
    }
    emit();

    // 4. SYNTHESIZE, and chart EVERY step that has something to show
    turn.status = "synthesizing";
    emit();
    const synthPrompt = buildSynthesisPrompt({
      question: args.question,
      approach: turn.approach ?? "",
      prior,
      steps: turn.steps.map((s, i) => ({
        goal: s.goal,
        facts: results[i] ? describeStepResult(results[i]!) : "(no result)",
        verdict: s.check?.verdict,
        note: s.check?.note,
        error: s.error,
      })),
    });
    const [synth] = await Promise.all([
      ask<unknown>({ ...synthPrompt, model: args.model, maxTokens: ANALYST_TOKENS.synthesis }),
      chartEveryStep({ turn, results, question: args.question, model: args.model, llm: ask }),
    ]);
    const parsed = parseSynthesisReply(synth);
    turn.answer =
      parsed.answer ||
      "The analysis completed but produced no write-up — the step results above stand on their own.";
    if (parsed.followUps.length > 0) turn.followUps = parsed.followUps;
    turn.chartStep = leadChartStep(turn.steps, headline);
    turn.status = "done";
    emit();
    return turn;
  } catch (e) {
    turn.error = (e as Error).message;
    turn.status = "error";
    emit();
    return turn;
  }
}

// ── Editing a step, and rewriting the findings ───────────────────────────
//
// Showing the SQL and refusing to let anyone change it is half a promise.
// An analyst who reads a step, spots the wrong filter, and can only start
// the whole question over is not a partner. So a step's SQL is editable and
// re-runnable ON ITS OWN — and because the findings above were written from
// the OLD numbers, the turn is marked stale until they are rewritten.

/**
 * Re-run one step with the user's SQL. Returns the patched step; the caller
 * decides where it lands. Never mutates its input.
 */
export async function rerunStep(args: {
  step: AnalystStep;
  sql: string;
  execute?: (sql: string) => Promise<QueryResult>;
}): Promise<AnalystStep> {
  const clean = assertSelectOnly(args.sql);
  const run = args.execute ?? (await import("@/lib/sqlEngine")).runQuery;
  const res = await run(clean);
  return {
    ...args.step,
    sql: clean,
    columns: res.columns,
    rows: res.rows.slice(0, ANALYST_ROW_CAP),
    rowCount: res.rows.length,
    edited: true,
    error: undefined,
    status: "done",
    // The previous verdict judged the previous query. Keeping it would let a
    // green "Check passed" vouch for SQL the analyst never saw.
    check: { verdict: "suspect", note: "Edited and re-run by hand — not self-checked." },
    // Same for the chart: it was chosen for the old result's shape.
    chart: undefined,
  };
}

/** Mark a turn's findings as predating its results (after a step re-run). */
export function withStaleAnswer(turn: AnalystTurn, steps: AnalystStep[]): AnalystTurn {
  return { ...turn, steps, answerStale: true };
}

/**
 * Rewrite the findings from the CURRENT step results, and re-chart the steps
 * whose results changed. This is the same synthesis the loop runs — not a
 * lighter one — so a rewritten answer is worth exactly as much as the first.
 */
export async function resynthesizeTurn(args: {
  turn: AnalystTurn;
  priorTurns: AnalystTurn[];
  model?: string;
  /** Model transport; defaults to the browser session. See LlmJsonFn. */
  llm?: LlmJsonFn;
  onUpdate?: (turn: AnalystTurn) => void;
}): Promise<AnalystTurn> {
  const ask: LlmJsonFn = args.llm ?? llmJson;
  const turn: AnalystTurn = {
    ...args.turn,
    steps: args.turn.steps.map((s) => ({ ...s })),
    status: "synthesizing",
  };
  args.onUpdate?.({ ...turn });
  // The stored trace is the only source here: a step's sample IS what the
  // reader can see, so the write-up is grounded in exactly that.
  const asResult = (s: AnalystStep): QueryResult | null =>
    s.rows && s.columns
      ? {
          columns: s.columns,
          rows: s.rows,
          row_count: s.rowCount ?? s.rows.length,
          total_matched: s.rowCount ?? s.rows.length,
          capped: (s.rowCount ?? 0) > s.rows.length,
          duration_ms: 0,
        }
      : null;
  const results = turn.steps.map(asResult);
  try {
    const prompt = buildSynthesisPrompt({
      question: turn.question,
      approach: turn.approach ?? "",
      prior: priorContext(args.priorTurns),
      steps: turn.steps.map((s, i) => ({
        goal: s.goal,
        facts: results[i] ? describeStepResult(results[i]!) : "(no result)",
        verdict: s.check?.verdict,
        note: s.check?.note,
        error: s.error,
      })),
    });
    const [synth] = await Promise.all([
      ask<unknown>({ ...prompt, model: args.model, maxTokens: ANALYST_TOKENS.synthesis }),
      chartEveryStep({ turn, results, question: turn.question, model: args.model, llm: ask }),
    ]);
    const parsed = parseSynthesisReply(synth);
    if (parsed.answer) turn.answer = parsed.answer;
    turn.followUps = parsed.followUps.length > 0 ? parsed.followUps : undefined;
    turn.chartStep = leadChartStep(turn.steps, turn.chartStep ?? 0);
    turn.answerStale = false;
    turn.status = "done";
  } catch (e) {
    // The old findings stay, and stay MARKED stale — the failure must not
    // quietly re-bless prose written for different numbers.
    turn.status = "done";
    turn.answerStale = true;
    turn.error = `Could not rewrite the findings: ${(e as Error).message}`;
  }
  args.onUpdate?.({ ...turn });
  return turn;
}
