/**
 * Shared helpers for AgentSwarms code exporters (LangGraph / CrewAI / OpenAI
 * Agents SDK). Keeps model-id handling, tool descriptions, and the
 * gateway-model warning identical across every generated target so they can't
 * drift apart.
 *
 * Generated by AgentSwarm — https://agentswarms.fyi
 */

/** Human-readable descriptions for the built-in swarm tool ids. */
export const TOOL_DESCRIPTIONS: Record<string, string> = {
  kb_search: "Search the attached knowledge base via vector similarity.",
  kb_graph_search: "Graph-aware search over the knowledge base (GraphRAG).",
  web_search: "Search the public web and return result snippets.",
  web_browse: "Fetch and read the contents of a web page.",
  n8n_run_workflow: "Trigger an n8n workflow and return its output.",
  mcp_call_tool: "Call a tool exposed by a connected MCP server.",
  calculator: "Evaluate an arithmetic expression and return the result.",
  datetime: "Return the current date and time.",
  weather: "Look up the current weather for a location.",
  sql_query: "Run a read-only SQL query over connected data tables.",
};

export function toolDescription(id: string): string {
  return TOOL_DESCRIPTIONS[id] || `${id} — implement your logic here.`;
}

/**
 * Strip *all* gateway/provider prefixes from a model id.
 *
 * AgentSwarms routes through a gateway, so models are stored as
 * `google/gemini-2.5-pro` or even `openrouter/openai/gpt-4o-mini`.
 * Native provider SDKs (OpenAI / Anthropic / Google) want the bare id, so we
 * take the final `/`-segment. This also yields the right value for OpenRouter
 * ids like `anthropic/claude-3.5-sonnet` → `claude-3.5-sonnet`.
 */
export function cleanModelId(model?: string): string {
  const m = (model || "gpt-4o").trim();
  const parts = m.split("/").filter(Boolean);
  return parts.length ? parts[parts.length - 1] : m;
}

/**
 * Loud warning emitted into every generated file's header. Gateway model names
 * are not guaranteed to match a provider's public model ids, and the keys the
 * platform used are never exported, so the user must wire their own.
 */
export const MODEL_ID_WARNING =
  'Model IDs below are AgentSwarms AI Gateway names (e.g. "google/gemini-3-flash-preview"). ' +
  "They may NOT match your provider's public model names — replace each with a real model " +
  "id and set the matching API key (OPENAI_API_KEY / ANTHROPIC_API_KEY / GOOGLE_API_KEY).";

/**
 * Tools, knowledge bases (RAG), guardrails and memory configured on the canvas
 * are surfaced as stubs/notes only — the exporter cannot reproduce the hosted
 * runtime wiring. Spelled out once here so every target says the same thing.
 */
export const FIDELITY_NOTE = [
  "Fidelity note — this scaffold is a runnable STARTER, not a 1:1 copy of the hosted run:",
  "  • Tool bodies are stubs (the platform's hosted tools are not portable).",
  "  • Knowledge-base / RAG retrieval is NOT wired — attach your own retriever.",
  "  • Guardrails and memory settings are not reproduced here.",
  "  • Condition routing and loop bodies are TODO stubs where present.",
];
