// What each common function takes and does: for formula autocomplete, the
// hint under the formula bar, and the AI assistant's context. Functions not
// listed here still work; they autocomplete by name alone.

export type FunctionHelp = { sig: string; desc: string; cat: string };

export const FUNCTION_HELP: Record<string, FunctionHelp> = {
  SUM: {
    sig: "SUM(number1, [number2], …)",
    desc: "Adds numbers; text and blanks in ranges are skipped.",
    cat: "Math",
  },
  SUMIF: {
    sig: "SUMIF(range, criteria, [sum_range])",
    desc: 'Sums where range meets criteria, e.g. ">10" or "ap*".',
    cat: "Math",
  },
  SUMIFS: {
    sig: "SUMIFS(sum_range, criteria_range1, criteria1, …)",
    desc: "Sums where every criteria pair is met.",
    cat: "Math",
  },
  AGGREGATE: {
    sig: "AGGREGATE(function_num, options, ref1, …) or (function_num, options, array, k)",
    desc: "A total that can leave out hidden rows, errors and nested subtotals.",
    cat: "Math",
  },
  "T.TEST": {
    sig: "T.TEST(array1, array2, tails, type)",
    desc: "Student's t-test: type 1 paired, 2 equal variances, 3 unequal; tails 1 or 2.",
    cat: "Statistical",
  },
  TTEST: {
    sig: "TTEST(array1, array2, tails, type)",
    desc: "T.TEST's older name.",
    cat: "Statistical",
  },
  "F.TEST": {
    sig: "F.TEST(array1, array2)",
    desc: "The two-tailed probability that two arrays' variances are not different.",
    cat: "Statistical",
  },
  FTEST: { sig: "FTEST(array1, array2)", desc: "F.TEST's older name.", cat: "Statistical" },
  "Z.TEST": {
    sig: "Z.TEST(array, x, [sigma])",
    desc: "The one-tailed P-value of a z-test of x against the array's mean.",
    cat: "Statistical",
  },
  ZTEST: { sig: "ZTEST(array, x, [sigma])", desc: "Z.TEST's older name.", cat: "Statistical" },
  "CHISQ.TEST": {
    sig: "CHISQ.TEST(actual_range, expected_range)",
    desc: "The chi-squared test of independence between observed and expected counts.",
    cat: "Statistical",
  },
  CHITEST: {
    sig: "CHITEST(actual_range, expected_range)",
    desc: "CHISQ.TEST's older name.",
    cat: "Statistical",
  },
  "MODE.MULT": {
    sig: "MODE.MULT(number1, [number2], …)",
    desc: "Every most frequent value, down a column, in the order they first appear.",
    cat: "Statistical",
  },
  COVAR: {
    sig: "COVAR(array1, array2)",
    desc: "The population covariance (COVARIANCE.P's older name).",
    cat: "Statistical",
  },
  PEARSON: {
    sig: "PEARSON(array1, array2)",
    desc: "The Pearson correlation coefficient, as CORREL.",
    cat: "Statistical",
  },
  STEYX: {
    sig: "STEYX(known_y's, known_x's)",
    desc: "The standard error of each predicted y in a linear regression.",
    cat: "Statistical",
  },
  "SKEW.P": {
    sig: "SKEW.P(number1, [number2], …)",
    desc: "The skewness of a population.",
    cat: "Statistical",
  },
  STDEVPA: {
    sig: "STDEVPA(value1, [value2], …)",
    desc: "A population's standard deviation, text as 0 and TRUE as 1.",
    cat: "Statistical",
  },
  VARPA: {
    sig: "VARPA(value1, [value2], …)",
    desc: "A population's variance, text as 0 and TRUE as 1.",
    cat: "Statistical",
  },
  PROB: {
    sig: "PROB(x_range, prob_range, lower_limit, [upper_limit])",
    desc: "The probability that a value falls between the limits.",
    cat: "Statistical",
  },
  SUMX2MY2: {
    sig: "SUMX2MY2(array_x, array_y)",
    desc: "The sum of x² − y² over the pairs.",
    cat: "Math",
  },
  SUMX2PY2: {
    sig: "SUMX2PY2(array_x, array_y)",
    desc: "The sum of x² + y² over the pairs.",
    cat: "Math",
  },
  SUMXMY2: {
    sig: "SUMXMY2(array_x, array_y)",
    desc: "The sum of (x − y)² over the pairs.",
    cat: "Math",
  },
  "BINOM.DIST.RANGE": {
    sig: "BINOM.DIST.RANGE(trials, probability_s, number_s, [number_s2])",
    desc: "The probability of a number of successes, or a range of them.",
    cat: "Statistical",
  },
  CONVERT: {
    sig: "CONVERT(number, from_unit, to_unit)",
    desc: 'A measurement in another unit of the same kind: "mi" to "km", "F" to "C", "kWh" to "BTU".',
    cat: "Engineering",
  },
  WRAPROWS: {
    sig: "WRAPROWS(vector, wrap_count, [pad_with])",
    desc: "A row or column folded into rows of that many values.",
    cat: "Dynamic array",
  },
  WRAPCOLS: {
    sig: "WRAPCOLS(vector, wrap_count, [pad_with])",
    desc: "A row or column folded into columns of that many values.",
    cat: "Dynamic array",
  },
  EXPAND: {
    sig: "EXPAND(array, rows, [columns], [pad_with])",
    desc: "The array grown to that size, the new cells padded (#N/A unless you say).",
    cat: "Dynamic array",
  },
  ARRAYTOTEXT: {
    sig: "ARRAYTOTEXT(array, [format])",
    desc: "An array as text: 0 lists the values, 1 writes it as an array constant.",
    cat: "Text",
  },
  VALUETOTEXT: {
    sig: "VALUETOTEXT(value, [format])",
    desc: "A value as text; format 1 puts text in quotes.",
    cat: "Text",
  },
  SHEET: {
    sig: "SHEET([value])",
    desc: "A sheet's number among the tabs, this one's when left out.",
    cat: "Information",
  },
  SHEETS: {
    sig: "SHEETS([reference])",
    desc: "How many sheets the workbook has.",
    cat: "Information",
  },
  AREAS: { sig: "AREAS(reference)", desc: "How many areas a reference has: 1.", cat: "Lookup" },
  NORMSDIST: {
    sig: "NORMSDIST(z)",
    desc: "The standard normal cumulative distribution (NORM.S.DIST's older name).",
    cat: "Statistical",
  },
  NORMSINV: {
    sig: "NORMSINV(probability)",
    desc: "The inverse of the standard normal (NORM.S.INV's older name).",
    cat: "Statistical",
  },
  NORMINV: {
    sig: "NORMINV(probability, mean, standard_dev)",
    desc: "The inverse of the normal distribution (NORM.INV's older name).",
    cat: "Statistical",
  },
  LENB: { sig: "LENB(text)", desc: "The same as LEN outside double-byte languages.", cat: "Text" },
  LEFTB: {
    sig: "LEFTB(text, [num_bytes])",
    desc: "The same as LEFT outside double-byte languages.",
    cat: "Text",
  },
  RIGHTB: {
    sig: "RIGHTB(text, [num_bytes])",
    desc: "The same as RIGHT outside double-byte languages.",
    cat: "Text",
  },
  MIDB: {
    sig: "MIDB(text, start_num, num_bytes)",
    desc: "The same as MID outside double-byte languages.",
    cat: "Text",
  },
  FINDB: {
    sig: "FINDB(find_text, within_text, [start_num])",
    desc: "The same as FIND outside double-byte languages.",
    cat: "Text",
  },
  SEARCHB: {
    sig: "SEARCHB(find_text, within_text, [start_num])",
    desc: "The same as SEARCH outside double-byte languages.",
    cat: "Text",
  },
  REPLACEB: {
    sig: "REPLACEB(old_text, start_num, num_bytes, new_text)",
    desc: "The same as REPLACE outside double-byte languages.",
    cat: "Text",
  },
  MDETERM: {
    sig: "MDETERM(array)",
    desc: "The determinant of a square block of numbers.",
    cat: "Math",
  },
  MINVERSE: {
    sig: "MINVERSE(array)",
    desc: "The inverse of a square block of numbers; #NUM! when it has none.",
    cat: "Math",
  },
  MUNIT: {
    sig: "MUNIT(dimension)",
    desc: "The identity matrix of that size.",
    cat: "Math",
  },
  "CEILING.PRECISE": {
    sig: "CEILING.PRECISE(number, [significance])",
    desc: "Rounds up, toward +∞, to a multiple of the significance, whatever the signs.",
    cat: "Math",
  },
  "FLOOR.PRECISE": {
    sig: "FLOOR.PRECISE(number, [significance])",
    desc: "Rounds down, toward −∞, to a multiple of the significance, whatever the signs.",
    cat: "Math",
  },
  "ISO.CEILING": {
    sig: "ISO.CEILING(number, [significance])",
    desc: "The same as CEILING.PRECISE.",
    cat: "Math",
  },
  FACTDOUBLE: {
    sig: "FACTDOUBLE(number)",
    desc: "The double factorial: 7!! is 7×5×3×1.",
    cat: "Math",
  },
  MULTINOMIAL: {
    sig: "MULTINOMIAL(number1, [number2], …)",
    desc: "(a+b+…)! divided by a!·b!·…",
    cat: "Math",
  },
  SERIESSUM: {
    sig: "SERIESSUM(x, n, m, coefficients)",
    desc: "A power series: the sum of each coefficient times x^(n + i·m).",
    cat: "Math",
  },
  SQRTPI: {
    sig: "SQRTPI(number)",
    desc: "The square root of number × π.",
    cat: "Math",
  },
  ACOSH: { sig: "ACOSH(number)", desc: "The inverse hyperbolic cosine.", cat: "Math" },
  ASINH: { sig: "ASINH(number)", desc: "The inverse hyperbolic sine.", cat: "Math" },
  ATANH: { sig: "ATANH(number)", desc: "The inverse hyperbolic tangent.", cat: "Math" },
  ACOT: { sig: "ACOT(number)", desc: "The arccotangent, from 0 to π.", cat: "Math" },
  ACOTH: { sig: "ACOTH(number)", desc: "The inverse hyperbolic cotangent.", cat: "Math" },
  COT: { sig: "COT(number)", desc: "The cotangent of an angle in radians.", cat: "Math" },
  COTH: { sig: "COTH(number)", desc: "The hyperbolic cotangent.", cat: "Math" },
  CSC: { sig: "CSC(number)", desc: "The cosecant of an angle in radians.", cat: "Math" },
  CSCH: { sig: "CSCH(number)", desc: "The hyperbolic cosecant.", cat: "Math" },
  SEC: { sig: "SEC(number)", desc: "The secant of an angle in radians.", cat: "Math" },
  SECH: { sig: "SECH(number)", desc: "The hyperbolic secant.", cat: "Math" },
  ERF: {
    sig: "ERF(lower_limit, [upper_limit])",
    desc: "The error function, from 0 to the lower limit or between the two.",
    cat: "Engineering",
  },
  "ERF.PRECISE": {
    sig: "ERF.PRECISE(x)",
    desc: "The error function from 0 to x.",
    cat: "Engineering",
  },
  ERFC: {
    sig: "ERFC(x)",
    desc: "The complementary error function, 1 − ERF(x).",
    cat: "Engineering",
  },
  "ERFC.PRECISE": {
    sig: "ERFC.PRECISE(x)",
    desc: "The complementary error function, 1 − ERF(x).",
    cat: "Engineering",
  },
  DELTA: {
    sig: "DELTA(number1, [number2])",
    desc: "1 if the two are equal, else 0.",
    cat: "Engineering",
  },
  GESTEP: {
    sig: "GESTEP(number, [step])",
    desc: "1 if the number is at least the step, else 0.",
    cat: "Engineering",
  },
  BESSELI: {
    sig: "BESSELI(x, n)",
    desc: "The modified Bessel function Iₙ(x).",
    cat: "Engineering",
  },
  BESSELJ: { sig: "BESSELJ(x, n)", desc: "The Bessel function Jₙ(x).", cat: "Engineering" },
  BESSELK: {
    sig: "BESSELK(x, n)",
    desc: "The modified Bessel function Kₙ(x).",
    cat: "Engineering",
  },
  BESSELY: {
    sig: "BESSELY(x, n)",
    desc: "The Bessel function Yₙ(x), or Weber function.",
    cat: "Engineering",
  },
  SUMPRODUCT: {
    sig: "SUMPRODUCT(array1, [array2], …)",
    desc: "Multiplies arrays element by element and sums.",
    cat: "Math",
  },
  AVERAGE: {
    sig: "AVERAGE(number1, [number2], …)",
    desc: "The mean of the numbers.",
    cat: "Statistical",
  },
  AVERAGEIF: {
    sig: "AVERAGEIF(range, criteria, [average_range])",
    desc: "Mean where range meets criteria.",
    cat: "Statistical",
  },
  AVERAGEIFS: {
    sig: "AVERAGEIFS(average_range, criteria_range1, criteria1, …)",
    desc: "Mean where every criteria pair is met.",
    cat: "Statistical",
  },
  COUNT: {
    sig: "COUNT(value1, [value2], …)",
    desc: "Counts cells holding numbers.",
    cat: "Statistical",
  },
  COUNTA: {
    sig: "COUNTA(value1, [value2], …)",
    desc: "Counts non-empty cells.",
    cat: "Statistical",
  },
  COUNTBLANK: { sig: "COUNTBLANK(range)", desc: "Counts empty cells.", cat: "Statistical" },
  COUNTIF: {
    sig: "COUNTIF(range, criteria)",
    desc: "Counts cells meeting criteria.",
    cat: "Statistical",
  },
  COUNTIFS: {
    sig: "COUNTIFS(criteria_range1, criteria1, …)",
    desc: "Counts rows meeting every criteria pair.",
    cat: "Statistical",
  },
  MIN: { sig: "MIN(number1, [number2], …)", desc: "The smallest number.", cat: "Statistical" },
  MAX: { sig: "MAX(number1, [number2], …)", desc: "The largest number.", cat: "Statistical" },
  MINIFS: {
    sig: "MINIFS(min_range, criteria_range1, criteria1, …)",
    desc: "Smallest where criteria are met.",
    cat: "Statistical",
  },
  MAXIFS: {
    sig: "MAXIFS(max_range, criteria_range1, criteria1, …)",
    desc: "Largest where criteria are met.",
    cat: "Statistical",
  },
  MEDIAN: { sig: "MEDIAN(number1, [number2], …)", desc: "The middle value.", cat: "Statistical" },
  STDEV: {
    sig: "STDEV(number1, [number2], …)",
    desc: "Sample standard deviation.",
    cat: "Statistical",
  },
  PERCENTILE: {
    sig: "PERCENTILE(array, k)",
    desc: "The k-th percentile (k between 0 and 1).",
    cat: "Statistical",
  },
  RANK: {
    sig: "RANK(number, ref, [order])",
    desc: "The rank of a number in a list.",
    cat: "Statistical",
  },
  LARGE: { sig: "LARGE(array, k)", desc: "The k-th largest value.", cat: "Statistical" },
  SMALL: { sig: "SMALL(array, k)", desc: "The k-th smallest value.", cat: "Statistical" },
  ROUND: { sig: "ROUND(number, num_digits)", desc: "Rounds half away from zero.", cat: "Math" },
  ROUNDUP: { sig: "ROUNDUP(number, num_digits)", desc: "Rounds away from zero.", cat: "Math" },
  ROUNDDOWN: { sig: "ROUNDDOWN(number, num_digits)", desc: "Rounds toward zero.", cat: "Math" },
  INT: { sig: "INT(number)", desc: "Rounds down to an integer.", cat: "Math" },
  MOD: {
    sig: "MOD(number, divisor)",
    desc: "The remainder, with the divisor's sign.",
    cat: "Math",
  },
  ABS: { sig: "ABS(number)", desc: "Absolute value.", cat: "Math" },
  POWER: { sig: "POWER(number, power)", desc: "number ^ power.", cat: "Math" },
  SQRT: { sig: "SQRT(number)", desc: "Square root.", cat: "Math" },
  IF: {
    sig: "IF(logical_test, [value_if_true], [value_if_false])",
    desc: "One of two values, by a condition.",
    cat: "Logical",
  },
  IFS: {
    sig: "IFS(test1, value1, [test2, value2], …)",
    desc: "The value of the first TRUE test.",
    cat: "Logical",
  },
  IFERROR: {
    sig: "IFERROR(value, value_if_error)",
    desc: "value, or the fallback when it is an error.",
    cat: "Logical",
  },
  IFNA: {
    sig: "IFNA(value, value_if_na)",
    desc: "value, or the fallback when it is #N/A.",
    cat: "Logical",
  },
  AND: {
    sig: "AND(logical1, [logical2], …)",
    desc: "TRUE when every argument is TRUE.",
    cat: "Logical",
  },
  OR: {
    sig: "OR(logical1, [logical2], …)",
    desc: "TRUE when any argument is TRUE.",
    cat: "Logical",
  },
  NOT: { sig: "NOT(logical)", desc: "Reverses TRUE and FALSE.", cat: "Logical" },
  SWITCH: {
    sig: "SWITCH(expression, value1, result1, …, [default])",
    desc: "The result for the first matching value.",
    cat: "Logical",
  },
  LAMBDA: {
    sig: "LAMBDA([parameter1, …], calculation)",
    desc: "A function of your own: call it, as LAMBDA(x, x*2)(3), or name it in Data → Names.",
    cat: "Logical",
  },
  MAP: {
    sig: "MAP(array1, [array2, …], lambda)",
    desc: "Each value of the arrays through a LAMBDA, as an array of the same size.",
    cat: "Logical",
  },
  REDUCE: {
    sig: "REDUCE([initial_value], array, lambda(accumulator, value))",
    desc: "Folds an array into one value, a LAMBDA call per value.",
    cat: "Logical",
  },
  SCAN: {
    sig: "SCAN([initial_value], array, lambda(accumulator, value))",
    desc: "REDUCE that keeps each step: a running total, for one.",
    cat: "Logical",
  },
  BYROW: {
    sig: "BYROW(array, lambda(row))",
    desc: "One value per row, from a LAMBDA given the row.",
    cat: "Logical",
  },
  BYCOL: {
    sig: "BYCOL(array, lambda(column))",
    desc: "One value per column, from a LAMBDA given the column.",
    cat: "Logical",
  },
  MAKEARRAY: {
    sig: "MAKEARRAY(rows, cols, lambda(row, col))",
    desc: "An array whose every value a LAMBDA computes from its row and column.",
    cat: "Logical",
  },
  ISOMITTED: {
    sig: "ISOMITTED(parameter)",
    desc: "TRUE when a call left out a LAMBDA's [optional] parameter.",
    cat: "Logical",
  },
  VLOOKUP: {
    sig: "VLOOKUP(lookup_value, table_array, col_index, [range_lookup])",
    desc: "Finds a row by its first column; FALSE for an exact match.",
    cat: "Lookup",
  },
  HLOOKUP: {
    sig: "HLOOKUP(lookup_value, table_array, row_index, [range_lookup])",
    desc: "Finds a column by its first row.",
    cat: "Lookup",
  },
  XLOOKUP: {
    sig: "XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])",
    desc: "Finds a value and returns the matching item; exact by default.",
    cat: "Lookup",
  },
  INDEX: {
    sig: "INDEX(array, row_num, [column_num])",
    desc: "The value at a row and column of a range.",
    cat: "Lookup",
  },
  MATCH: {
    sig: "MATCH(lookup_value, lookup_array, [match_type])",
    desc: "The position of a value; 0 for exact.",
    cat: "Lookup",
  },
  XMATCH: {
    sig: "XMATCH(lookup_value, lookup_array, [match_mode], [search_mode])",
    desc: "The position of a value; exact by default.",
    cat: "Lookup",
  },
  CHOOSE: { sig: "CHOOSE(index, value1, [value2], …)", desc: "The index-th value.", cat: "Lookup" },
  UNIQUE: {
    sig: "UNIQUE(array, [by_col], [exactly_once])",
    desc: "The distinct rows; spills.",
    cat: "Dynamic array",
  },
  SORT: {
    sig: "SORT(array, [sort_index], [sort_order])",
    desc: "The rows sorted by a column; spills.",
    cat: "Dynamic array",
  },
  SORTBY: {
    sig: "SORTBY(array, by_array1, [order1], …)",
    desc: "The rows sorted by other arrays; spills.",
    cat: "Dynamic array",
  },
  FILTER: {
    sig: "FILTER(array, include, [if_empty])",
    desc: "The rows where include is TRUE; spills.",
    cat: "Dynamic array",
  },
  SEQUENCE: {
    sig: "SEQUENCE(rows, [columns], [start], [step])",
    desc: "A grid of numbers; spills.",
    cat: "Dynamic array",
  },
  TRANSPOSE: {
    sig: "TRANSPOSE(array)",
    desc: "Swaps rows and columns; spills.",
    cat: "Dynamic array",
  },
  CONCAT: { sig: "CONCAT(text1, [text2], …)", desc: "Joins text.", cat: "Text" },
  TEXTJOIN: {
    sig: "TEXTJOIN(delimiter, ignore_empty, text1, …)",
    desc: "Joins text with a delimiter.",
    cat: "Text",
  },
  LEFT: { sig: "LEFT(text, [num_chars])", desc: "Characters from the start.", cat: "Text" },
  RIGHT: { sig: "RIGHT(text, [num_chars])", desc: "Characters from the end.", cat: "Text" },
  MID: { sig: "MID(text, start_num, num_chars)", desc: "Characters from the middle.", cat: "Text" },
  LEN: { sig: "LEN(text)", desc: "The number of characters.", cat: "Text" },
  TRIM: { sig: "TRIM(text)", desc: "Removes extra spaces.", cat: "Text" },
  UPPER: { sig: "UPPER(text)", desc: "Upper case.", cat: "Text" },
  LOWER: { sig: "LOWER(text)", desc: "Lower case.", cat: "Text" },
  PROPER: { sig: "PROPER(text)", desc: "Capitalises each word.", cat: "Text" },
  SUBSTITUTE: {
    sig: "SUBSTITUTE(text, old_text, new_text, [instance_num])",
    desc: "Replaces text by content.",
    cat: "Text",
  },
  REPLACE: {
    sig: "REPLACE(old_text, start_num, num_chars, new_text)",
    desc: "Replaces text by position.",
    cat: "Text",
  },
  FIND: {
    sig: "FIND(find_text, within_text, [start_num])",
    desc: "Position of text, case-sensitive.",
    cat: "Text",
  },
  SEARCH: {
    sig: "SEARCH(find_text, within_text, [start_num])",
    desc: "Position of text, with wildcards.",
    cat: "Text",
  },
  TEXT: {
    sig: "TEXT(value, format_text)",
    desc: 'A number as text in a format, e.g. "yyyy-mm-dd" or "0.0%".',
    cat: "Text",
  },
  VALUE: { sig: "VALUE(text)", desc: "Text to a number.", cat: "Text" },
  EXACT: { sig: "EXACT(text1, text2)", desc: "TRUE if identical, case-sensitive.", cat: "Text" },
  DATE: { sig: "DATE(year, month, day)", desc: "A date from its parts.", cat: "Date" },
  TODAY: { sig: "TODAY()", desc: "Today's date.", cat: "Date" },
  NOW: { sig: "NOW()", desc: "The current date and time.", cat: "Date" },
  YEAR: { sig: "YEAR(serial_number)", desc: "The year of a date.", cat: "Date" },
  MONTH: { sig: "MONTH(serial_number)", desc: "The month of a date (1–12).", cat: "Date" },
  DAY: { sig: "DAY(serial_number)", desc: "The day of the month.", cat: "Date" },
  WEEKDAY: {
    sig: "WEEKDAY(serial_number, [return_type])",
    desc: "Day of the week: 1 = Sunday by default; 2 or 11 from Monday, 12–17 from Tuesday–Sunday.",
    cat: "Date",
  },
  DAYS360: {
    sig: "DAYS360(start_date, end_date, [method])",
    desc: "Days between two dates on a 360-day year (US method; TRUE for European).",
    cat: "Date",
  },
  EDATE: {
    sig: "EDATE(start_date, months)",
    desc: "The date months before or after.",
    cat: "Date",
  },
  EOMONTH: { sig: "EOMONTH(start_date, months)", desc: "The last day of a month.", cat: "Date" },
  DATEDIF: {
    sig: "DATEDIF(start_date, end_date, unit)",
    desc: 'Whole "Y", "M" or "D" between two dates.',
    cat: "Date",
  },
  NETWORKDAYS: {
    sig: "NETWORKDAYS(start_date, end_date, [holidays])",
    desc: "Working days between two dates.",
    cat: "Date",
  },
  ISBLANK: { sig: "ISBLANK(value)", desc: "TRUE if empty.", cat: "Information" },
  ISNUMBER: { sig: "ISNUMBER(value)", desc: "TRUE if a number.", cat: "Information" },
  ISTEXT: { sig: "ISTEXT(value)", desc: "TRUE if text.", cat: "Information" },
  ISERROR: { sig: "ISERROR(value)", desc: "TRUE if any error.", cat: "Information" },
  PMT: {
    sig: "PMT(rate, nper, pv, [fv], [type])",
    desc: "The payment for a loan.",
    cat: "Financial",
  },
  NPV: { sig: "NPV(rate, value1, [value2], …)", desc: "Net present value.", cat: "Financial" },
  IRR: { sig: "IRR(values, [guess])", desc: "Internal rate of return.", cat: "Financial" },
  CUMIPMT: {
    sig: "CUMIPMT(rate, nper, pv, start_period, end_period, type)",
    desc: "Interest paid on a loan between two periods.",
    cat: "Financial",
  },
  CUMPRINC: {
    sig: "CUMPRINC(rate, nper, pv, start_period, end_period, type)",
    desc: "Principal paid on a loan between two periods.",
    cat: "Financial",
  },
  MIRR: {
    sig: "MIRR(values, finance_rate, reinvest_rate)",
    desc: "Rate of return with separate borrowing and reinvestment rates.",
    cat: "Financial",
  },
};
