import type { Notebook, NotebookSummary } from "./types";

export const NOTEBOOKS: NotebookSummary[] = [
  // Foundations Lab — start here. Raw API, no frameworks.
  { id: "fnd-prompt-engineering", title: "Prompt Engineering & Text Generation Lab", description: "System vs user roles, few-shot, chain-of-thought, persona, structured JSON, and temperature — built on raw fetch with clear, beginner-friendly explanations.", difficulty: "beginner", tags: ["content"], subgroup: "Prompting Basics", cellCount: 15 },
  { id: "fnd-multimodal-image", title: "Image & Multimodal Lab", description: "Generate images with Gemini Nano Banana, describe and compare images with vision models, OCR a receipt into JSON, and round-trip describe-then-redraw.", difficulty: "beginner", tags: ["content"], subgroup: "Prompting Basics", cellCount: 11 },

  // ⚠️ Failure Modes Lab — the most important notebook in the course.
  { id: "fail-modes-lab", title: "⚠️ Failure Modes Lab — Real-World Agent Failures & How to Fix Them", description: "The single most important notebook in the course. Reproduce 12 real failure modes seen in production — hallucinations, sycophancy, runaway loops, prompt injection, RAG poisoning, context rot, cost blow-ups, lost-in-the-middle, schema breakage, goal drift, cascading errors — then ship the exact fix for each.", difficulty: "advanced", tags: ["agent", "evaluation"], subgroup: "Critical Reading", cellCount: 38 },

  // Agentic Evals — how to grade LLM/agent outputs reliably
  { id: "eval-fundamentals",      title: "Evaluation Fundamentals — Deterministic vs Semantic & LLM-as-Judge", description: "Why classic unit tests fail with LLMs. Build a strict regex check, a semantic similarity check using embeddings, and a structured LLM judge graded on a rubric.", difficulty: "beginner",     tags: ["evaluation"],          subgroup: "Evaluation Fundamentals", cellCount: 9 },
  { id: "eval-programmatic",      title: "Programmatic Evaluation — Ground Truth, Exact Match & Calculations", description: "When answers are objectively correct (facts, numbers, classifications), grade them with code. Builds a city dataset and runs four eval types plus an accuracy scoreboard.", difficulty: "beginner",     tags: ["evaluation"],          subgroup: "Evaluation Fundamentals", cellCount: 11 },
  { id: "eval-judge-jury",        title: "LLM-as-a-Judge & Jury — Rubrics, Consensus & Confidence",            description: "Grade open-ended answers with a single rubric-based judge, then upgrade to a 3-judge jury. Use the spread between judges as a confidence signal.", difficulty: "intermediate", tags: ["evaluation"],          subgroup: "Evaluation Fundamentals", cellCount: 6 },
  { id: "eval-meta-judge",        title: "Evaluating Your Judge — TPR/TNR, Repeatability & Length Bias",      description: "Your judge is just another model — calibrate it first. Build a human-labeled benchmark, measure TPR/TNR, test repeatability, and detect length bias.", difficulty: "intermediate", tags: ["evaluation"],          subgroup: "Evaluation Fundamentals", cellCount: 11 },
  { id: "eval-rag-triad",         title: "RAG Evaluation Triad — Context Relevance, Faithfulness, Answer Relevance", description: "Three judges that together diagnose any RAG failure. Includes a broken pipeline where the answer is right for the wrong reasons — and the triad catches it.", difficulty: "intermediate", tags: ["evaluation", "rag"],   subgroup: "RAG & Agent Evaluation", cellCount: 10 },
  { id: "eval-agent-trajectory",  title: "Agent Trajectory & Path Efficiency",                                  description: "Grade the path, not just the destination. Capture an agent's tool-call trajectory and score it on selection, redundancy, and total budget.", difficulty: "intermediate", tags: ["evaluation", "agent"], subgroup: "RAG & Agent Evaluation", cellCount: 8 },
  { id: "eval-red-team",          title: "Red Team & Guardrails — Measuring Block Rate Against Jailbreaks",   description: "Fire 10 known prompt-injection and data-exfiltration attacks at an agent. Add input + output middleware until the block rate hits 100%.", difficulty: "advanced",     tags: ["evaluation", "agent"], subgroup: "Safety & Operations", cellCount: 10 },
  { id: "eval-operational",       title: "Operational Metrics — Cost, Latency, TTFT, TPS & Throughput",       description: "Measure what production cares about: per-request cost, end-to-end latency, streamed TTFT vs TTLT, inter-token latency, and concurrent throughput.", difficulty: "advanced",     tags: ["evaluation"],          subgroup: "Safety & Operations", cellCount: 8 },

  // LangChain Course — subgrouped for readability
  { id: "lc-fundamentals", title: "LangChain Fundamentals", description: "Chat output, multi-turn message types, streaming, model_kwargs, simple chains, and tool-call inspection.", difficulty: "beginner", tags: ["langchain"], subgroup: "Foundations", cellCount: 5 },
  { id: "lc-documents", title: "Images & PDFs with LangChain", description: "Hands-on image lab (vision Q&A on multiple images) and PDF processing (extract text with pdfjs, then summarise with a LangChain chain).", difficulty: "beginner", tags: ["langchain"], subgroup: "Foundations", cellCount: 4 },
  { id: "lc-tools-agents", title: "Tools, Agents & Multi-Tool Orchestration", description: "Define tools with Zod (the Pydantic of TS), build a real agent loop, observe tool-call messages, and orchestrate multiple tools.", difficulty: "intermediate", tags: ["langchain", "agent"], subgroup: "Agents & Workflows", cellCount: 4 },
  { id: "lc-workflows", title: "Memory, Human-in-the-Loop & Structured Output", description: "LangGraph state machines: persistent memory with MemorySaver checkpoints, interrupt-before approval, and structured extraction.", difficulty: "advanced", tags: ["langchain", "langgraph", "agent"], subgroup: "Agents & Workflows", cellCount: 4 },
  { id: "lc-rag", title: "Embeddings, RAG & RAG-with-Tools", description: "Text splitters, OpenAI-compatible embeddings, an in-memory vector store, a grounded RAG chain, and a RAG-backed tool.", difficulty: "advanced", tags: ["langchain", "rag"], subgroup: "Retrieval & RAG", cellCount: 4 },

  // LlamaIndex.ts track
  { id: "li-nodes-documents", title: "From Raw Text to Nodes (Document vs. TextNode)", description: "LlamaIndex's Document/TextNode model: attach metadata, define how a Document is parsed into atomic Nodes, and watch metadata flow into each chunk.", difficulty: "beginner", tags: ["llamaindex", "rag"], subgroup: "Core Fundamentals", cellCount: 4 },
  { id: "li-vector-engine", title: "VectorStoreIndex & Query Engine Basics", description: "The fastest path to RAG in LlamaIndex.ts: build a VectorStoreIndex, expose it as a QueryEngine, then switch to a ChatEngine and compare the payloads.", difficulty: "beginner", tags: ["llamaindex", "rag"], subgroup: "Core Fundamentals", cellCount: 4 },
  { id: "li-sentence-window", title: "Sentence Window Retrieval", description: "Embed single sentences for precision, then expand to a configurable window of surrounding sentences at query time. Slide the window and see the prompt grow.", difficulty: "intermediate", tags: ["llamaindex", "rag"], subgroup: "Advanced RAG Patterns", cellCount: 4 },
  { id: "li-router-engine", title: "Router Query Engine (The Smart Switch)", description: "An LLM-selected router that dispatches a question to either a vector index (semantic lookup) or a summary index (global synthesis).", difficulty: "intermediate", tags: ["llamaindex", "rag", "routing"], subgroup: "Advanced RAG Patterns", cellCount: 4 },
  { id: "li-subquestion-engine", title: "Sub-Question Query Engine (Decomposing Prompts)", description: "Take a comparative question, decompose it into independent sub-questions, run them across separate per-document indices in parallel, then synthesise the answer.", difficulty: "advanced", tags: ["llamaindex", "rag"], subgroup: "Advanced RAG Patterns", cellCount: 5 },
  { id: "li-data-agent", title: "Context-Augmented Data Agent", description: "An autonomous agent equipped with multiple query engines as tools. It decides which index to search, when to cross-reference, and when it has enough to answer.", difficulty: "advanced", tags: ["llamaindex", "agent", "rag"], subgroup: "Data Agents", cellCount: 4 },
  { id: "li-evaluation", title: "Evaluating Faithfulness & Answer Relevancy (RAG Triad)", description: "Score a RAG answer with two LLM judges — Faithfulness (is the answer grounded in context?) and Answer Relevancy (does it answer the question?). Corrupt the context and watch the scores collapse.", difficulty: "advanced", tags: ["llamaindex", "rag", "evaluation"], subgroup: "Production Evaluation", cellCount: 5 },

  // Google ADK (Agent Development Kit) — concepts ported to TypeScript
  { id: "adk-fundamentals",      title: "ADK Fundamentals — LlmAgent, Instructions & the Run Loop", description: "Google ADK's headline primitive is LlmAgent: model + instruction + description + tools. Port the exact shape to TypeScript and run a real session loop.", difficulty: "beginner",     tags: ["agent", "structured-output"], subgroup: "Core Fundamentals", cellCount: 7 },
  { id: "adk-function-tools",    title: "FunctionTool — Typed Tools the ADK Way",                    description: "Mirror ADK's FunctionTool in TypeScript with Zod. Build three tools (weather, FX, attractions) and watch the agent loop decide which to call.", difficulty: "beginner",     tags: ["agent", "structured-output"], subgroup: "Core Fundamentals", cellCount: 6 },
  { id: "adk-workflow-agents",   title: "Workflow Agents — Sequential & Parallel",                   description: "ADK's pure-orchestration agents: SequentialAgent runs children in order, ParallelAgent fans them out. Build a writer→editor pipeline and a multi-critic review board.", difficulty: "intermediate", tags: ["agent", "multi-agent"], subgroup: "Workflow & Multi-Agent", cellCount: 7 },
  { id: "adk-loop-agent",        title: "LoopAgent & Shared State — Self-Critique Until It's Good", description: "ADK's LoopAgent + session.state, ported. Build the canonical generator→critic loop that improves a draft until a structured critic says ship.", difficulty: "intermediate", tags: ["agent", "multi-agent", "evaluation"], subgroup: "Workflow & Multi-Agent", cellCount: 7 },
  { id: "adk-multi-agent",       title: "Multi-Agent with sub_agents & transfer_to_agent",            description: "Build a customer-support routing tree (billing / technical / refunds / human). A cheap router emits transfer_to_agent decisions; specialists handle each turn.", difficulty: "intermediate", tags: ["agent", "multi-agent", "routing"], subgroup: "Workflow & Multi-Agent", cellCount: 7 },
  { id: "adk-callbacks-safety",  title: "Callbacks & Safety — Lifecycle Hooks, Guardrails, Budgets", description: "ADK's before_model / after_model / before_tool / after_tool callbacks, ported. Bolt on PII filter, tool allowlist, profanity scrubber, and a hard budget — all without touching the agent's prompt.", difficulty: "advanced",     tags: ["agent", "evaluation"],          subgroup: "Safety & Observability", cellCount: 6 },

  // OpenAI Agents SDK Track
  { id: "oai-fundamentals",       title: "Agents, Instructions & the Run Loop",                              description: "The core mental model: Agent (instructions + model + tools), Runner that drives the loop, and tools defined with Zod. Hand-rolled so every step is visible.", difficulty: "beginner",     tags: ["agent", "structured-output"], subgroup: "Core Fundamentals", cellCount: 5 },
  { id: "oai-handoffs",           title: "Handoffs & the Triage Pattern",                                    description: "Multi-agent routing the OpenAI way: a triage agent decides which specialist (Billing, Tech, Sales) should answer, then hands control off via a synthetic transfer tool.", difficulty: "intermediate", tags: ["agent", "multi-agent", "routing"], subgroup: "Multi-Agent", cellCount: 4 },
  { id: "oai-guardrails",         title: "Input & Output Guardrails (Tripwires)",                            description: "Wrap an agent with cheap classifier guardrails that can raise a tripwire and abort the run before money is spent or unsafe content goes out.", difficulty: "intermediate", tags: ["agent", "evaluation"], subgroup: "Safety", cellCount: 4 },
  { id: "oai-structured-output",  title: "Structured Output with outputType + Zod",                          description: "Force the agent to return a typed object instead of free text. Strict JSON Schema mode, Zod validation, and automatic retry on validation failure.", difficulty: "intermediate", tags: ["agent", "structured-output"], subgroup: "Outputs", cellCount: 4 },
  { id: "oai-sessions-memory",    title: "Sessions — Multi-Turn Memory the SDK Way",                         description: "Persist conversation history across run() calls. Build an in-memory session, then see how a SQLite/Redis session works underneath.", difficulty: "intermediate", tags: ["agent"], subgroup: "Memory", cellCount: 4 },
  { id: "oai-streaming-tracing",  title: "Streaming, Lifecycle Hooks & Tracing",                             description: "Stream tokens live, hook into agent_start / tool_end / handoff events, and emit OpenTelemetry-compatible traces — the pieces that make agents debuggable in production.", difficulty: "advanced",     tags: ["agent", "evaluation"], subgroup: "Observability", cellCount: 4 },

  // Vercel AI SDK Track
  { id: "vai-fundamentals",       title: "generateText, streamText & Provider Routing",                     description: "The two workhorse functions and the unified provider({ model }) API. One signature works across OpenAI, Anthropic, Google, Mistral, Groq, Bedrock and 30+ others.", difficulty: "beginner",     tags: ["content"], subgroup: "Core Fundamentals", cellCount: 4 },
  { id: "vai-structured-objects", title: "generateObject & streamObject (Typed JSON with Zod)",             description: "Force the model into a Zod-typed object — and stream it field-by-field as it generates. The shape that powers most Vercel SDK production apps.", difficulty: "beginner",     tags: ["structured-output"], subgroup: "Core Fundamentals", cellCount: 4 },
  { id: "vai-tools",              title: "Tools — tool() + execute + Multi-Step",                            description: "Define typed tools with the SDK's tool() helper, then let the model call them in a multi-step loop driven by stopWhen / stepCountIs / onStepFinish.", difficulty: "intermediate", tags: ["agent"], subgroup: "Tools & Agents", cellCount: 3 },
  { id: "vai-agents",             title: "The Agent Class — stopWhen, prepareStep, hasToolCall",             description: "Wrap the multi-step loop in the SDK's Agent class. Use hasToolCall to exit on a sentinel tool, and prepareStep to swap models or tools per step.", difficulty: "advanced",     tags: ["agent"], subgroup: "Tools & Agents", cellCount: 3 },
  { id: "vai-embeddings-rag",     title: "embed, embedMany & cosineSimilarity (Mini RAG)",                   description: "The embedding helpers — one call for a single embedding, one for batches, plus cosineSimilarity. Build a complete grounded-RAG pipeline.", difficulty: "intermediate", tags: ["rag"], subgroup: "Embeddings & RAG", cellCount: 5 },
  { id: "vai-ui-streaming",       title: "UI Message Streaming, useChat & Tracing",                         description: "How streamText().toUIMessageStreamResponse() talks to the useChat hook over a typed SSE protocol. Plus experimental_telemetry for OpenTelemetry traces.", difficulty: "advanced",     tags: ["content"], subgroup: "UI & Observability", cellCount: 5 },

  // Mastra Track — typed agent framework
  { id: "mst-fundamentals", title: "Mastra Fundamentals — Agent, instructions, generate & stream", description: "The Mastra mental model: a typed Agent (id + name + instructions + model + tools + memory) wired into a root Mastra container. Use generate() for batch and stream() for live chat — both with the same configuration.", difficulty: "beginner",     tags: ["agent"], subgroup: "Core Fundamentals", cellCount: 5 },
  { id: "mst-tools",        title: "Tools — createTool, Zod schemas & multi-tool agent loops",     description: "Mastra's typed tool model: createTool() with Zod input/output schemas, attach a map of tools to an Agent, watch the model orchestrate them across a multi-step loop with real fetch-driven side effects.", difficulty: "beginner",     tags: ["agent", "structured-output"], subgroup: "Core Fundamentals", cellCount: 5 },
  { id: "mst-workflows",    title: "Workflows — createWorkflow, createStep, .then/.parallel/.branch", description: "Typed step graphs: createStep() units with input/output Zod schemas composed via .then / .parallel / .branch / .dountil, run as one typed call. Plus a human-in-the-loop suspend example.", difficulty: "intermediate", tags: ["agent", "structured-output"], subgroup: "Workflows", cellCount: 5 },
  { id: "mst-memory",       title: "Memory — threads, working memory & semantic recall",            description: "Mastra's three-layer memory: a recent message window, a structured working-memory object the model rewrites, and semantic recall over an embedded message archive — built and queried against real embeddings.", difficulty: "intermediate", tags: ["agent", "rag"], subgroup: "Memory & State", cellCount: 7 },
  { id: "mst-rag",          title: "RAG — MDocument, chunking, embedMany & createVectorQueryTool",  description: "End-to-end RAG: build an MDocument, chunk with the recursive strategy, embed with embedMany, store in an in-browser vector index, and expose it to an Agent as a real createVectorQueryTool over an e-bike support knowledge base.", difficulty: "intermediate", tags: ["agent", "rag"], subgroup: "RAG", cellCount: 5 },
  { id: "mst-evals",        title: "Evals & Observability — scorers, telemetry & lifecycle hooks",  description: "Attach scorers (faithfulness, answer-relevancy, custom rubric) to an agent, capture every run's score in a sampled telemetry stream, and wire lifecycle hooks (onStepStart/onStepFinish/onAgentFinish) for production observability.", difficulty: "advanced",     tags: ["agent", "evaluation"], subgroup: "Evals & Observability", cellCount: 5 },

  // VoltAgent Track — open-source TypeScript agent framework + observability platform
  { id: "volt-fundamentals", title: "VoltAgent Fundamentals — Agent, instructions, generateText & streamText", description: "The VoltAgent mental model: an Agent (name + instructions + model + tools + memory) registered on a `new VoltAgent({ agents })` root. generateText() for batch, streamText() for live chat.", difficulty: "beginner",     tags: ["agent"],                       subgroup: "Core Fundamentals", cellCount: 5 },
  { id: "volt-tools",        title: "Tools — createTool, Zod parameters & multi-tool agent loops",            description: "VoltAgent's typed tool model: createTool() with Zod parameters, attach a list of tools to an Agent, watch the model orchestrate them across a bounded multi-step loop with real fetch-driven side effects.", difficulty: "beginner",     tags: ["agent", "structured-output"], subgroup: "Core Fundamentals", cellCount: 4 },
  { id: "volt-memory",       title: "Memory — threads, working memory & semantic recall",                     description: "VoltAgent's three-layer Memory: a conversation message window, structured working memory the model rewrites, and semantic recall over an embedded message archive — built and queried against real embeddings.", difficulty: "intermediate", tags: ["agent", "rag"],                subgroup: "State & Memory", cellCount: 3 },
  { id: "volt-rag",          title: "RAG — Retrievers, embeddings & two retrieval patterns",                  description: "Build a real BaseRetriever over an e-bike support handbook, then attach it two ways — directly (every message auto-retrieves) vs as a tool (the model decides). Contrast the answers.", difficulty: "intermediate", tags: ["agent", "rag"],                subgroup: "RAG", cellCount: 3 },
  { id: "volt-guardrails",   title: "Guardrails — input bundles, output filters & tripwires",                 description: "VoltAgent's guardrail system: profanity, PII redaction, prompt-injection tripwires on input, plus secret-leak scrubbing on output. Fires 6 test inputs at a real agent and measures the block rate.", difficulty: "intermediate", tags: ["agent", "evaluation"],         subgroup: "Safety", cellCount: 3 },
  { id: "volt-mcp",          title: "MCP — connect an Agent to a Model Context Protocol server",              description: "MCPConfiguration discovers a server's tools/list, namespaces them, and hands them to an Agent as native tools. Build a tiny MCP-shaped filesystem server, expose its tools, and watch the model call them.", difficulty: "advanced",     tags: ["agent"],                       subgroup: "Integrations", cellCount: 3 },
  { id: "volt-voice",        title: "Voice — TTS, STT & a voice-enabled Agent",                                description: "The @voltagent/voice surface: OpenAIVoiceProvider with voice.speak()/voice.listen(), attached to an Agent for full listen → reason → speak loops. Hotel-concierge example end to end.", difficulty: "intermediate", tags: ["agent", "content"],            subgroup: "Multimodal", cellCount: 3 },
  { id: "volt-workflows",    title: "Workflows — createWorkflowChain, andThen, andAgent, andAll, andWhen",   description: "VoltAgent's typed step graph: composed via .andThen / .andAgent / .andAll / .andWhen with Zod input/output schemas. Build a 5-step content-multiplexer pipeline and watch the trace.", difficulty: "intermediate", tags: ["agent", "structured-output"], subgroup: "Workflows", cellCount: 3 },

  // Standalone Agents
  { id: "sa-hello-tool", title: "Hello World API Fetcher — Intro to Tool Calling", description: "A first agent with one tool: fetch the current weather for any city. This is the smallest useful tool-calling pattern.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 2 },
  { id: "sa-json-enforcer", title: "Text → JSON Enforcer (Structured Output)", description: "Turn a messy email into a strict JSON object using a Zod schema and withStructuredOutput.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-mini-rag", title: "Basic Document RAG (Embeddings & Retrieval)", description: "Chunk a small text, embed it, and answer questions grounded in that text with an in-memory retriever.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 2 },
  { id: "sa-pii-sanitizer", title: "PII Sanitizer (Middleware Guardrails)", description: "An agent that scrubs credit cards, SSNs, emails and names from a payload before it reaches a model.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-web-summarizer", title: "Web Scraper & Summarizer", description: "Use Firecrawl to fetch a URL, then summarise its core argument. Swap URLs to see grounding behavior change.", difficulty: "beginner", tags: ["agent", "langchain", "firecrawl"], cellCount: 1 },
  { id: "sa-ticket-classifier", title: "Customer Support Ticket Classifier", description: "Intent-routing agent: reads a complaint and outputs category, priority, sentiment, and first response.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-text-to-sql", title: "Text-to-SQL Query Generator", description: "Give the agent a schema, ask in natural language, get SQL back. Edit the schema and watch constraints matter.", difficulty: "intermediate", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-code-reviewer", title: "Code Reviewer (Prompt Chaining)", description: "Two-step chain: step one finds bugs, step two rewrites the code with comments explaining each fix.", difficulty: "intermediate", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-translator", title: "Local Dialect Translation Agent", description: "Translate text into specific dialects — Gen-Z slang, legal jargon, Shakespeare, or customer-friendly support tone.", difficulty: "beginner", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "sa-self-correction", title: "Self-Correction Loop (Basic Reflection)", description: "Generator → Critic → Rewriter loop. Make the rubric strict and watch the second draft improve.", difficulty: "intermediate", tags: ["agent", "langchain"], cellCount: 1 },
  { id: "mas-orchestrator-workers", title: "The Orchestrator & Workers Pattern", description: "A lead Orchestrator splits a complex task into independent subtasks, fans them out to specialized workers, then synthesizes the final answer.", difficulty: "advanced", tags: ["langgraph", "multi-agent", "agent"], cellCount: 5 },
  { id: "mas-plan-execute", title: "Plan & Execute Crew (ReAct Loop)", description: "A classic two-agent setup. The Planner breaks a request into a numbered plan; the Executor performs each step with tools; the graph loops until done.", difficulty: "intermediate", tags: ["langgraph", "multi-agent", "agent"], cellCount: 5 },
  { id: "mas-hitl-invoice", title: "Human-In-The-Loop Invoice Approver", description: "An agent reads an invoice and prepares to pay it. If the amount is over a threshold, the graph interrupts for human approval before continuing.", difficulty: "intermediate", tags: ["langgraph", "multi-agent", "agent"], cellCount: 5 },
  { id: "mas-supervisor-router", title: "Multi-Agent Supervisor Router", description: "A Lead Orchestrator routes each incoming task to either the Math Specialist, Research Specialist, or Writer Specialist based on state.", difficulty: "intermediate", tags: ["langgraph", "multi-agent", "agent"], cellCount: 4 },
  { id: "mas-coder-reviewer", title: "Coder, Reviewer & Tester Loop (Cyclic Graph)", description: "Three agents in a true cycle. The Coder writes code, the Reviewer critiques it, the Tester executes assertions, and the graph loops until passing.", difficulty: "advanced", tags: ["langgraph", "multi-agent", "agent"], cellCount: 5 },
  { id: "mas-red-blue", title: "Red Team vs. Blue Team Evaluator", description: "Two agents face off across a state graph. The Red Team tries to extract secrets; the Blue Team patches the prompt until the attack fails.", difficulty: "advanced", tags: ["langgraph", "multi-agent", "agent"], cellCount: 5 },
  { id: "ent-mcp-server", title: "Building a Custom TypeScript MCP Server", description: "Build an MCP (Model Context Protocol) server from scratch in TypeScript with tool schemas, resource handlers, and local testing.", difficulty: "advanced", tags: ["agent", "langchain"], cellCount: 3 },
  { id: "ent-semantic-chunking", title: "Semantic Chunking Evaluator", description: "Naive character-based chunking butchers ideas mid-sentence. This notebook builds a semantic chunker and scores chunk quality before retrieval.", difficulty: "advanced", tags: ["langchain", "agent"], cellCount: 5 },
  { id: "ent-cost-routing", title: "Dynamic Cost-Optimized Routing Gateway", description: "Stop sending every query to the most expensive model. This notebook builds a gateway that routes easy requests to cheap models and escalates hard ones.", difficulty: "advanced", tags: ["langchain", "agent"], cellCount: 5 },
  { id: "news-agent", title: "City News Agent — real LangChain, step by step", description: "Build a tool-using agent with @langchain/openai + @langchain/core that researches a city, summarizes sources, and produces structured output.", difficulty: "beginner", tags: ["agent", "langchain", "firecrawl"], cellCount: 6 },
  { id: "rw-refund-agent", title: "Autonomous E-Commerce Refund Agent (HITL)", description: "End-to-end customer-service automation: order lookup, RAG over the refund policy, sentiment-aware reasoning, refund decision, and human approval routing.", difficulty: "advanced", tags: ["langgraph", "rag", "hitl", "agent", "real-world"], cellCount: 7 },
  { id: "rw-content-multiplexer", title: "Multi-Platform Content Multiplexer", description: "Take any blog URL, scrape it with Firecrawl, then fan out to two specialist agents that create a LinkedIn post, Twitter thread, and newsletter blurb.", difficulty: "intermediate", tags: ["agent", "firecrawl", "multi-agent", "content", "real-world", "structured-output"], cellCount: 4 },
  { id: "rw-github-triager", title: "GitHub Issue Triager & Auto-Responder", description: "Classify an incoming GitHub issue (severity + sentiment + labels), search a mini knowledge base, and generate a structured maintainer response.", difficulty: "intermediate", tags: ["agent", "structured-output", "devops", "real-world", "rag"], cellCount: 4 },
  { id: "rw-contract-analyzer", title: "Automated Contract Risk Analyzer", description: "Run a freelance contract through a structured Risk Analysis Rubric — clause extraction, risk scoring, missing-term detection, and negotiation bullets.", difficulty: "advanced", tags: ["agent", "structured-output", "legaltech", "real-world"], cellCount: 4 },
  { id: "rw-investment-analyst", title: "Personal AI Investment Analyst", description: "Pull a stock ticker's latest earnings summary and live sentiment headlines, compute mock fundamentals, and output a structured investment brief.", difficulty: "intermediate", tags: ["agent", "structured-output", "fintech", "real-world"], cellCount: 4 },
  { id: "rw-travel-optimizer", title: "Travel Itinerary & Budget Optimizer", description: "A LangGraph agent that plans a 3-day Tokyo trip under a strict USD budget, loops when costs exceed the cap, and returns a day-by-day itinerary.", difficulty: "advanced", tags: ["langgraph", "agent", "consumer", "routing", "real-world"], cellCount: 6 },
];

const NOTEBOOK_LOADERS = {
  "fnd-prompt-engineering": () => import("./fnd-prompt-engineering.notebook").then((m) => m.fndPromptEngineeringNotebook),
  "fnd-multimodal-image": () => import("./fnd-multimodal-image.notebook").then((m) => m.fndMultimodalImageNotebook),
  "fail-modes-lab": () => import("./fail-modes.notebook").then((m) => m.failModesNotebook),
  "eval-fundamentals": () => import("./eval-fundamentals.notebook").then((m) => m.evalFundamentalsNotebook),
  "eval-programmatic": () => import("./eval-programmatic.notebook").then((m) => m.evalProgrammaticNotebook),
  "eval-judge-jury": () => import("./eval-judge-jury.notebook").then((m) => m.evalJudgeJuryNotebook),
  "eval-meta-judge": () => import("./eval-meta-judge.notebook").then((m) => m.evalMetaJudgeNotebook),
  "eval-rag-triad": () => import("./eval-rag-triad.notebook").then((m) => m.evalRagTriadNotebook),
  "eval-agent-trajectory": () => import("./eval-agent-trajectory.notebook").then((m) => m.evalAgentTrajectoryNotebook),
  "eval-red-team": () => import("./eval-red-team.notebook").then((m) => m.evalRedTeamNotebook),
  "eval-operational": () => import("./eval-operational.notebook").then((m) => m.evalOperationalNotebook),
  "lc-fundamentals": () => import("./lc-fundamentals.notebook").then((m) => m.lcFundamentalsNotebook),
  "lc-documents": () => import("./lc-documents.notebook").then((m) => m.lcDocumentsNotebook),
  "lc-tools-agents": () => import("./lc-tools-agents.notebook").then((m) => m.lcToolsAgentsNotebook),
  "lc-workflows": () => import("./lc-workflows.notebook").then((m) => m.lcWorkflowsNotebook),
  "lc-rag": () => import("./lc-rag.notebook").then((m) => m.lcRagNotebook),
  "li-nodes-documents": () => import("./li-nodes-documents.notebook").then((m) => m.liNodesDocumentsNotebook),
  "li-vector-engine": () => import("./li-vector-engine.notebook").then((m) => m.liVectorEngineNotebook),
  "li-sentence-window": () => import("./li-sentence-window.notebook").then((m) => m.liSentenceWindowNotebook),
  "li-router-engine": () => import("./li-router-engine.notebook").then((m) => m.liRouterEngineNotebook),
  "li-subquestion-engine": () => import("./li-subquestion-engine.notebook").then((m) => m.liSubQuestionEngineNotebook),
  "li-data-agent": () => import("./li-data-agent.notebook").then((m) => m.liDataAgentNotebook),
  "li-evaluation": () => import("./li-evaluation.notebook").then((m) => m.liEvaluationNotebook),
  "adk-fundamentals": () => import("./adk-fundamentals.notebook").then((m) => m.adkFundamentalsNotebook),
  "adk-function-tools": () => import("./adk-function-tools.notebook").then((m) => m.adkFunctionToolsNotebook),
  "adk-workflow-agents": () => import("./adk-workflow-agents.notebook").then((m) => m.adkWorkflowAgentsNotebook),
  "adk-loop-agent": () => import("./adk-loop-agent.notebook").then((m) => m.adkLoopAgentNotebook),
  "adk-multi-agent": () => import("./adk-multi-agent.notebook").then((m) => m.adkMultiAgentNotebook),
  "adk-callbacks-safety": () => import("./adk-callbacks-safety.notebook").then((m) => m.adkCallbacksSafetyNotebook),
  "oai-fundamentals": () => import("./oai-fundamentals.notebook").then((m) => m.oaiFundamentalsNotebook),
  "oai-handoffs": () => import("./oai-handoffs.notebook").then((m) => m.oaiHandoffsNotebook),
  "oai-guardrails": () => import("./oai-guardrails.notebook").then((m) => m.oaiGuardrailsNotebook),
  "oai-structured-output": () => import("./oai-structured-output.notebook").then((m) => m.oaiStructuredOutputNotebook),
  "oai-sessions-memory": () => import("./oai-sessions-memory.notebook").then((m) => m.oaiSessionsMemoryNotebook),
  "oai-streaming-tracing": () => import("./oai-streaming-tracing.notebook").then((m) => m.oaiStreamingTracingNotebook),
  "vai-fundamentals": () => import("./vai-fundamentals.notebook").then((m) => m.vaiFundamentalsNotebook),
  "vai-structured-objects": () => import("./vai-structured-objects.notebook").then((m) => m.vaiStructuredObjectsNotebook),
  "vai-tools": () => import("./vai-tools.notebook").then((m) => m.vaiToolsNotebook),
  "vai-agents": () => import("./vai-agents.notebook").then((m) => m.vaiAgentsNotebook),
  "vai-embeddings-rag": () => import("./vai-embeddings-rag.notebook").then((m) => m.vaiEmbeddingsRagNotebook),
  "vai-ui-streaming": () => import("./vai-ui-streaming.notebook").then((m) => m.vaiUiStreamingNotebook),
  "mst-fundamentals": () => import("./mst-fundamentals.notebook").then((m) => m.mstFundamentalsNotebook),
  "mst-tools": () => import("./mst-tools.notebook").then((m) => m.mstToolsNotebook),
  "mst-workflows": () => import("./mst-workflows.notebook").then((m) => m.mstWorkflowsNotebook),
  "mst-memory": () => import("./mst-memory.notebook").then((m) => m.mstMemoryNotebook),
  "mst-rag": () => import("./mst-rag.notebook").then((m) => m.mstRagNotebook),
  "mst-evals": () => import("./mst-evals.notebook").then((m) => m.mstEvalsNotebook),
  "volt-fundamentals": () => import("./volt-fundamentals.notebook").then((m) => m.voltFundamentalsNotebook),
  "volt-tools": () => import("./volt-tools.notebook").then((m) => m.voltToolsNotebook),
  "volt-memory": () => import("./volt-memory.notebook").then((m) => m.voltMemoryNotebook),
  "volt-rag": () => import("./volt-rag.notebook").then((m) => m.voltRagNotebook),
  "volt-guardrails": () => import("./volt-guardrails.notebook").then((m) => m.voltGuardrailsNotebook),
  "volt-mcp": () => import("./volt-mcp.notebook").then((m) => m.voltMcpNotebook),
  "volt-voice": () => import("./volt-voice.notebook").then((m) => m.voltVoiceNotebook),
  "volt-workflows": () => import("./volt-workflows.notebook").then((m) => m.voltWorkflowsNotebook),
  "sa-hello-tool": () => import("./sa-hello-tool.notebook").then((m) => m.saHelloToolNotebook),
  "sa-json-enforcer": () => import("./sa-json-enforcer.notebook").then((m) => m.saJsonEnforcerNotebook),
  "sa-mini-rag": () => import("./sa-mini-rag.notebook").then((m) => m.saMiniRagNotebook),
  "sa-pii-sanitizer": () => import("./sa-pii-sanitizer.notebook").then((m) => m.saPiiSanitizerNotebook),
  "sa-web-summarizer": () => import("./sa-web-summarizer.notebook").then((m) => m.saWebSummarizerNotebook),
  "sa-ticket-classifier": () => import("./sa-ticket-classifier.notebook").then((m) => m.saTicketClassifierNotebook),
  "sa-text-to-sql": () => import("./sa-text-to-sql.notebook").then((m) => m.saTextToSqlNotebook),
  "sa-code-reviewer": () => import("./sa-code-reviewer.notebook").then((m) => m.saCodeReviewerNotebook),
  "sa-translator": () => import("./sa-translator.notebook").then((m) => m.saTranslatorNotebook),
  "sa-self-correction": () => import("./sa-self-correction.notebook").then((m) => m.saSelfCorrectionNotebook),
  "mas-orchestrator-workers": () => import("./mas-orchestrator-workers.notebook").then((m) => m.masOrchestratorWorkersNotebook),
  "mas-plan-execute": () => import("./mas-plan-execute.notebook").then((m) => m.masPlanExecuteNotebook),
  "mas-hitl-invoice": () => import("./mas-hitl-invoice.notebook").then((m) => m.masHitlInvoiceNotebook),
  "mas-supervisor-router": () => import("./mas-supervisor-router.notebook").then((m) => m.masSupervisorRouterNotebook),
  "mas-coder-reviewer": () => import("./mas-coder-reviewer.notebook").then((m) => m.masCoderReviewerNotebook),
  "mas-red-blue": () => import("./mas-red-blue.notebook").then((m) => m.masRedBlueNotebook),
  "ent-mcp-server": () => import("./ent-mcp-server.notebook").then((m) => m.entMcpServerNotebook),
  "ent-semantic-chunking": () => import("./ent-semantic-chunking.notebook").then((m) => m.entSemanticChunkingNotebook),
  "ent-cost-routing": () => import("./ent-cost-routing.notebook").then((m) => m.entCostRoutingNotebook),
  "news-agent": () => import("./news-agent.notebook").then((m) => m.newsAgentNotebook),
  "rw-refund-agent": () => import("./rw-refund-agent.notebook").then((m) => m.rwRefundAgentNotebook),
  "rw-content-multiplexer": () => import("./rw-content-multiplexer.notebook").then((m) => m.rwContentMultiplexerNotebook),
  "rw-github-triager": () => import("./rw-github-triager.notebook").then((m) => m.rwGithubTriagerNotebook),
  "rw-contract-analyzer": () => import("./rw-contract-analyzer.notebook").then((m) => m.rwContractAnalyzerNotebook),
  "rw-investment-analyst": () => import("./rw-investment-analyst.notebook").then((m) => m.rwInvestmentAnalystNotebook),
  "rw-travel-optimizer": () => import("./rw-travel-optimizer.notebook").then((m) => m.rwTravelOptimizerNotebook),
} satisfies Record<string, () => Promise<Notebook>>;

export function getNotebookSummary(id: string): NotebookSummary | undefined {
  return NOTEBOOKS.find((notebook) => notebook.id === id);
}

export async function getNotebook(id: string): Promise<Notebook | undefined> {
  const loadNotebook = NOTEBOOK_LOADERS[id as keyof typeof NOTEBOOK_LOADERS];
  return loadNotebook?.();
}
