#!/usr/bin/env node
// Generate src/routeTree.gen.ts.
//
//   node scripts/generate-routes.mjs
//
// WHY THIS EXISTS. The route tree is generated by the TanStack Router plugin
// during `vite dev` / `vite build`, and it is gitignored on purpose — tracking
// it produced a meaningless diff on nearly every branch and merge conflicts
// nobody could resolve usefully.
//
// But `src/router.tsx` imports it, so TYPECHECKING depends on a build artifact.
// On a machine that has ever run the dev server the file is sitting there and
// everything looks fine; on a fresh clone — which is exactly what CI is — it is
// absent and `tsc --noEmit` fails with:
//
//   src/router.tsx(2): Cannot find module './routeTree.gen'
//
// followed by ~40 cascading errors that name innocent route files, because
// every typed `navigate("/…")` loses its route union. CI ran typecheck BEFORE
// build, so the artifact never existed when it was needed, and the whole
// pipeline failed on commits that changed nothing but a banner image.
//
// This makes the dependency explicit and cheap to satisfy: run it before
// typechecking, in CI and on a fresh clone alike. It is the same generator the
// Vite plugin uses, so it produces the same file.
import { Generator, getConfig } from "@tanstack/router-generator";

const root = process.cwd();

// The footer the TanStack START plugin appends on top of the plain router
// generator. It is what registers this app's router type with
// `@tanstack/react-start`, and without it the generated file is subtly
// different from what `vite build` produces — the kind of difference that shows
// up later as a confusing type error rather than here as a diff.
//
// Passed through the generator's own `routeTreeFileFooter` option rather than
// deep-imported from the plugin's internals (it is not in that package's
// exports map, so importing it would break on any refactor). The equivalence is
// proved rather than assumed: tests/unit/routeTreeGeneration.test.ts pins this
// against the committed output of a real build.
const START_FOOTER = [
  [
    ``,
    `import type { getRouter } from './router.tsx'`,
    `import type { startInstance } from './start.ts'`,
    `declare module '@tanstack/react-start' {`,
    `  interface Register {`,
    `    ssr: true`,
    `    router: Awaited<ReturnType<typeof getRouter>>`,
    `    config: Awaited<ReturnType<typeof startInstance.getOptions>>`,
    `  }`,
    `}`,
  ].join("\n"),
];

// No tsr.config.json in this repo — the plugin runs on its defaults, so the
// generator has to as well or the two would disagree about where routes live.
const config = getConfig({ routeTreeFileFooter: START_FOOTER }, root);

await new Generator({ config, root }).run();

console.log(`generated ${config.generatedRouteTree}`);
