/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DocsSwarmsRouteImport } from './routes/docs.swarms'
import { Route as DocsSkillsRouteImport } from './routes/docs.skills'
import { Route as DocsPlaygroundRouteImport } from './routes/docs.playground'
import { Route as DocsNotebooksRouteImport } from './routes/docs.notebooks'
import { Route as DocsIntegrationsRouteImport } from './routes/docs.integrations'
import { Route as DocsDebuggingRouteImport } from './routes/docs.debugging'
import { Route as DocsDashboardRouteImport } from './routes/docs.dashboard'
import { Route as DocsAnalyticsRouteImport } from './routes/docs.analytics'
import { Route as DocsAgentsRouteImport } from './routes/docs.agents'
import { Route as DocsAccountRouteImport } from './routes/docs.account'
import { Route as ApiPythonKbRouteImport } from './routes/api/python-kb'
import { Route as ApiPythonChatRouteImport } from './routes/api/python-chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiEmbedRouteImport } from './routes/api/embed'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBiRouteImport } from './routes/api/bi'
import { Route as ApiA2aRouteImport } from './routes/api/a2a'
import { Route as AuthenticatedTracesRouteImport } from './routes/_authenticated/traces'
import { Route as AuthenticatedSwarmsRouteImport } from './routes/_authenticated/swarms'
import { Route as AuthenticatedSkillsRouteImport } from './routes/_authenticated/skills'
import { Route as AuthenticatedSemanticsRouteImport } from './routes/_authenticated/semantics'
import { Route as AuthenticatedSecretsRouteImport } from './routes/_authenticated/secrets'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedPromptCompareRouteImport } from './routes/_authenticated/prompt-compare'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground'
import { Route as AuthenticatedNotebooksRouteImport } from './routes/_authenticated/notebooks'
import { Route as AuthenticatedModelRegistryRouteImport } from './routes/_authenticated/model-registry'
import { Route as AuthenticatedMcpRouteImport } from './routes/_authenticated/mcp'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedImagePlaygroundRouteImport } from './routes/_authenticated/image-playground'
import { Route as AuthenticatedEmbedsRouteImport } from './routes/_authenticated/embeds'
import { Route as AuthenticatedDataSqlRouteImport } from './routes/_authenticated/data-sql'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedBiRouteImport } from './routes/_authenticated/bi'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ShareBiSlugRouteImport } from './routes/share.bi.$slug'
import { Route as EmbedSwarmKeyRouteImport } from './routes/embed.swarm.$key'
import { Route as EmbedBiKeyRouteImport } from './routes/embed.bi.$key'
import { Route as EmbedAgentKeyRouteImport } from './routes/embed.agent.$key'
import { Route as ApiWarehouseSchemaRouteImport } from './routes/api/warehouse/schema'
import { Route as ApiWarehouseQueryRouteImport } from './routes/api/warehouse/query'
import { Route as ApiTemplatesProvisionRouteImport } from './routes/api/templates.provision'
import { Route as ApiSwarmRunRouteImport } from './routes/api/swarm.run'
import { Route as ApiSkillsGenerateRouteImport } from './routes/api/skills.generate'
import { Route as ApiNotebookRuntimeRouteImport } from './routes/api/notebook.runtime'
import { Route as ApiKbIngestUrlRouteImport } from './routes/api/kb/ingest-url'
import { Route as ApiKbIngestGithubRouteImport } from './routes/api/kb/ingest-github'
import { Route as ApiKbBuildGraphRouteImport } from './routes/api/kb/build-graph'
import { Route as ApiExamSubmitMcqRouteImport } from './routes/api/exam.submit-mcq'
import { Route as ApiExamStartRouteImport } from './routes/api/exam.start'
import { Route as ApiExamEvaluateRouteImport } from './routes/api/exam.evaluate'
import { Route as ApiEmbedChatRouteImport } from './routes/api/embed.chat'
import { Route as ApiEmailSendRouteImport } from './routes/api/email/send'
import { Route as ApiCertificateIdRouteImport } from './routes/api/certificate.$id'
import { Route as ApiBiCronRouteImport } from './routes/api/bi.cron'
import { Route as ApiAuthSsoConfigRouteImport } from './routes/api/auth/sso-config'
import { Route as AuthenticatedBiDashboardIdRouteImport } from './routes/_authenticated/bi_.$dashboardId'
import { Route as AuthenticatedAnalyticsObservabilityRouteImport } from './routes/_authenticated/analytics_.observability'
import { Route as AuthenticatedAdminRuntimeRouteImport } from './routes/_authenticated/admin.runtime'
import { Route as AuthenticatedAdminIamRouteImport } from './routes/_authenticated/admin.iam'
import { Route as ApiPublicHooksRefreshModelRegistryRouteImport } from './routes/api/public/hooks/refresh-model-registry'
import { Route as ApiPublicHooksGenerateExamSetRouteImport } from './routes/api/public/hooks/generate-exam-set'
import { Route as ApiNotebookRuntimeSourceRouteImport } from './routes/api/notebook.runtime.source'
import { Route as ApiNotebookRuntimeResultRouteImport } from './routes/api/notebook.runtime.result'
import { Route as ApiNotebookRuntimeReapRouteImport } from './routes/api/notebook.runtime.reap'
import { Route as AuthenticatedNotebooksSampleSampleSlugRouteImport } from './routes/_authenticated/notebooks.sample.$sampleSlug'
import { Route as AuthenticatedNotebooksPyPyNotebookIdRouteImport } from './routes/_authenticated/notebooks.py.$pyNotebookId'
import { Route as AuthenticatedAnalyticsObservabilityRunIdRouteImport } from './routes/_authenticated/analytics_.observability.$runId'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSwarmsRoute = DocsSwarmsRouteImport.update({
  id: '/swarms',
  path: '/swarms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSkillsRoute = DocsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPlaygroundRoute = DocsPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DocsRoute,
} as any)
const DocsNotebooksRoute = DocsNotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntegrationsRoute = DocsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDebuggingRoute = DocsDebuggingRouteImport.update({
  id: '/debugging',
  path: '/debugging',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDashboardRoute = DocsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAnalyticsRoute = DocsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAccountRoute = DocsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DocsRoute,
} as any)
const ApiPythonKbRoute = ApiPythonKbRouteImport.update({
  id: '/api/python-kb',
  path: '/api/python-kb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPythonChatRoute = ApiPythonChatRouteImport.update({
  id: '/api/python-chat',
  path: '/api/python-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedRoute = ApiEmbedRouteImport.update({
  id: '/api/embed',
  path: '/api/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiRoute = ApiBiRouteImport.update({
  id: '/api/bi',
  path: '/api/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiA2aRoute = ApiA2aRouteImport.update({
  id: '/api/a2a',
  path: '/api/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracesRoute = AuthenticatedTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSwarmsRoute = AuthenticatedSwarmsRouteImport.update({
  id: '/swarms',
  path: '/swarms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkillsRoute = AuthenticatedSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSemanticsRoute = AuthenticatedSemanticsRouteImport.update({
  id: '/semantics',
  path: '/semantics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecretsRoute = AuthenticatedSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromptCompareRoute =
  AuthenticatedPromptCompareRouteImport.update({
    id: '/prompt-compare',
    path: '/prompt-compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotebooksRoute = AuthenticatedNotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelRegistryRoute =
  AuthenticatedModelRegistryRouteImport.update({
    id: '/model-registry',
    path: '/model-registry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMcpRoute = AuthenticatedMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImagePlaygroundRoute =
  AuthenticatedImagePlaygroundRouteImport.update({
    id: '/image-playground',
    path: '/image-playground',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmbedsRoute = AuthenticatedEmbedsRouteImport.update({
  id: '/embeds',
  path: '/embeds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataSqlRoute = AuthenticatedDataSqlRouteImport.update({
  id: '/data-sql',
  path: '/data-sql',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiRoute = AuthenticatedBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShareBiSlugRoute = ShareBiSlugRouteImport.update({
  id: '/share/bi/$slug',
  path: '/share/bi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedSwarmKeyRoute = EmbedSwarmKeyRouteImport.update({
  id: '/embed/swarm/$key',
  path: '/embed/swarm/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedBiKeyRoute = EmbedBiKeyRouteImport.update({
  id: '/embed/bi/$key',
  path: '/embed/bi/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAgentKeyRoute = EmbedAgentKeyRouteImport.update({
  id: '/embed/agent/$key',
  path: '/embed/agent/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarehouseSchemaRoute = ApiWarehouseSchemaRouteImport.update({
  id: '/api/warehouse/schema',
  path: '/api/warehouse/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarehouseQueryRoute = ApiWarehouseQueryRouteImport.update({
  id: '/api/warehouse/query',
  path: '/api/warehouse/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesProvisionRoute = ApiTemplatesProvisionRouteImport.update({
  id: '/api/templates/provision',
  path: '/api/templates/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwarmRunRoute = ApiSwarmRunRouteImport.update({
  id: '/api/swarm/run',
  path: '/api/swarm/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsGenerateRoute = ApiSkillsGenerateRouteImport.update({
  id: '/api/skills/generate',
  path: '/api/skills/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebookRuntimeRoute = ApiNotebookRuntimeRouteImport.update({
  id: '/api/notebook/runtime',
  path: '/api/notebook/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbIngestUrlRoute = ApiKbIngestUrlRouteImport.update({
  id: '/api/kb/ingest-url',
  path: '/api/kb/ingest-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbIngestGithubRoute = ApiKbIngestGithubRouteImport.update({
  id: '/api/kb/ingest-github',
  path: '/api/kb/ingest-github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKbBuildGraphRoute = ApiKbBuildGraphRouteImport.update({
  id: '/api/kb/build-graph',
  path: '/api/kb/build-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamSubmitMcqRoute = ApiExamSubmitMcqRouteImport.update({
  id: '/api/exam/submit-mcq',
  path: '/api/exam/submit-mcq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamStartRoute = ApiExamStartRouteImport.update({
  id: '/api/exam/start',
  path: '/api/exam/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamEvaluateRoute = ApiExamEvaluateRouteImport.update({
  id: '/api/exam/evaluate',
  path: '/api/exam/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmbedChatRoute = ApiEmbedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiEmbedRoute,
} as any)
const ApiEmailSendRoute = ApiEmailSendRouteImport.update({
  id: '/api/email/send',
  path: '/api/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificateIdRoute = ApiCertificateIdRouteImport.update({
  id: '/api/certificate/$id',
  path: '/api/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBiCronRoute = ApiBiCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => ApiBiRoute,
} as any)
const ApiAuthSsoConfigRoute = ApiAuthSsoConfigRouteImport.update({
  id: '/api/auth/sso-config',
  path: '/api/auth/sso-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBiDashboardIdRoute =
  AuthenticatedBiDashboardIdRouteImport.update({
    id: '/bi_/$dashboardId',
    path: '/bi/$dashboardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsObservabilityRoute =
  AuthenticatedAnalyticsObservabilityRouteImport.update({
    id: '/analytics_/observability',
    path: '/analytics/observability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRuntimeRoute =
  AuthenticatedAdminRuntimeRouteImport.update({
    id: '/admin/runtime',
    path: '/admin/runtime',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIamRoute = AuthenticatedAdminIamRouteImport.update({
  id: '/admin/iam',
  path: '/admin/iam',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksRefreshModelRegistryRoute =
  ApiPublicHooksRefreshModelRegistryRouteImport.update({
    id: '/api/public/hooks/refresh-model-registry',
    path: '/api/public/hooks/refresh-model-registry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateExamSetRoute =
  ApiPublicHooksGenerateExamSetRouteImport.update({
    id: '/api/public/hooks/generate-exam-set',
    path: '/api/public/hooks/generate-exam-set',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiNotebookRuntimeSourceRoute =
  ApiNotebookRuntimeSourceRouteImport.update({
    id: '/source',
    path: '/source',
    getParentRoute: () => ApiNotebookRuntimeRoute,
  } as any)
const ApiNotebookRuntimeResultRoute =
  ApiNotebookRuntimeResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => ApiNotebookRuntimeRoute,
  } as any)
const ApiNotebookRuntimeReapRoute = ApiNotebookRuntimeReapRouteImport.update({
  id: '/reap',
  path: '/reap',
  getParentRoute: () => ApiNotebookRuntimeRoute,
} as any)
const AuthenticatedNotebooksSampleSampleSlugRoute =
  AuthenticatedNotebooksSampleSampleSlugRouteImport.update({
    id: '/sample/$sampleSlug',
    path: '/sample/$sampleSlug',
    getParentRoute: () => AuthenticatedNotebooksRoute,
  } as any)
const AuthenticatedNotebooksPyPyNotebookIdRoute =
  AuthenticatedNotebooksPyPyNotebookIdRouteImport.update({
    id: '/py/$pyNotebookId',
    path: '/py/$pyNotebookId',
    getParentRoute: () => AuthenticatedNotebooksRoute,
  } as any)
const AuthenticatedAnalyticsObservabilityRunIdRoute =
  AuthenticatedAnalyticsObservabilityRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthenticatedAnalyticsObservabilityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/bi': typeof AuthenticatedBiRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-sql': typeof AuthenticatedDataSqlRoute
  '/embeds': typeof AuthenticatedEmbedsRoute
  '/image-playground': typeof AuthenticatedImagePlaygroundRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/model-registry': typeof AuthenticatedModelRegistryRoute
  '/notebooks': typeof AuthenticatedNotebooksRouteWithChildren
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/prompt-compare': typeof AuthenticatedPromptCompareRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/secrets': typeof AuthenticatedSecretsRoute
  '/semantics': typeof AuthenticatedSemanticsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/swarms': typeof AuthenticatedSwarmsRoute
  '/traces': typeof AuthenticatedTracesRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/bi': typeof ApiBiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/embed': typeof ApiEmbedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/python-chat': typeof ApiPythonChatRoute
  '/api/python-kb': typeof ApiPythonKbRoute
  '/docs/account': typeof DocsAccountRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/debugging': typeof DocsDebuggingRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/notebooks': typeof DocsNotebooksRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/swarms': typeof DocsSwarmsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/docs/': typeof DocsIndexRoute
  '/admin/iam': typeof AuthenticatedAdminIamRoute
  '/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/analytics/observability': typeof AuthenticatedAnalyticsObservabilityRouteWithChildren
  '/bi/$dashboardId': typeof AuthenticatedBiDashboardIdRoute
  '/api/auth/sso-config': typeof ApiAuthSsoConfigRoute
  '/api/bi/cron': typeof ApiBiCronRoute
  '/api/certificate/$id': typeof ApiCertificateIdRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/embed/chat': typeof ApiEmbedChatRoute
  '/api/exam/evaluate': typeof ApiExamEvaluateRoute
  '/api/exam/start': typeof ApiExamStartRoute
  '/api/exam/submit-mcq': typeof ApiExamSubmitMcqRoute
  '/api/kb/build-graph': typeof ApiKbBuildGraphRoute
  '/api/kb/ingest-github': typeof ApiKbIngestGithubRoute
  '/api/kb/ingest-url': typeof ApiKbIngestUrlRoute
  '/api/notebook/runtime': typeof ApiNotebookRuntimeRouteWithChildren
  '/api/skills/generate': typeof ApiSkillsGenerateRoute
  '/api/swarm/run': typeof ApiSwarmRunRoute
  '/api/templates/provision': typeof ApiTemplatesProvisionRoute
  '/api/warehouse/query': typeof ApiWarehouseQueryRoute
  '/api/warehouse/schema': typeof ApiWarehouseSchemaRoute
  '/embed/agent/$key': typeof EmbedAgentKeyRoute
  '/embed/bi/$key': typeof EmbedBiKeyRoute
  '/embed/swarm/$key': typeof EmbedSwarmKeyRoute
  '/share/bi/$slug': typeof ShareBiSlugRoute
  '/analytics/observability/$runId': typeof AuthenticatedAnalyticsObservabilityRunIdRoute
  '/notebooks/py/$pyNotebookId': typeof AuthenticatedNotebooksPyPyNotebookIdRoute
  '/notebooks/sample/$sampleSlug': typeof AuthenticatedNotebooksSampleSampleSlugRoute
  '/api/notebook/runtime/reap': typeof ApiNotebookRuntimeReapRoute
  '/api/notebook/runtime/result': typeof ApiNotebookRuntimeResultRoute
  '/api/notebook/runtime/source': typeof ApiNotebookRuntimeSourceRoute
  '/api/public/hooks/generate-exam-set': typeof ApiPublicHooksGenerateExamSetRoute
  '/api/public/hooks/refresh-model-registry': typeof ApiPublicHooksRefreshModelRegistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/bi': typeof AuthenticatedBiRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-sql': typeof AuthenticatedDataSqlRoute
  '/embeds': typeof AuthenticatedEmbedsRoute
  '/image-playground': typeof AuthenticatedImagePlaygroundRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/mcp': typeof AuthenticatedMcpRoute
  '/model-registry': typeof AuthenticatedModelRegistryRoute
  '/notebooks': typeof AuthenticatedNotebooksRouteWithChildren
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/prompt-compare': typeof AuthenticatedPromptCompareRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/secrets': typeof AuthenticatedSecretsRoute
  '/semantics': typeof AuthenticatedSemanticsRoute
  '/skills': typeof AuthenticatedSkillsRoute
  '/swarms': typeof AuthenticatedSwarmsRoute
  '/traces': typeof AuthenticatedTracesRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/bi': typeof ApiBiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/embed': typeof ApiEmbedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/python-chat': typeof ApiPythonChatRoute
  '/api/python-kb': typeof ApiPythonKbRoute
  '/docs/account': typeof DocsAccountRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/debugging': typeof DocsDebuggingRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/notebooks': typeof DocsNotebooksRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/swarms': typeof DocsSwarmsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/docs': typeof DocsIndexRoute
  '/admin/iam': typeof AuthenticatedAdminIamRoute
  '/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/analytics/observability': typeof AuthenticatedAnalyticsObservabilityRouteWithChildren
  '/bi/$dashboardId': typeof AuthenticatedBiDashboardIdRoute
  '/api/auth/sso-config': typeof ApiAuthSsoConfigRoute
  '/api/bi/cron': typeof ApiBiCronRoute
  '/api/certificate/$id': typeof ApiCertificateIdRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/embed/chat': typeof ApiEmbedChatRoute
  '/api/exam/evaluate': typeof ApiExamEvaluateRoute
  '/api/exam/start': typeof ApiExamStartRoute
  '/api/exam/submit-mcq': typeof ApiExamSubmitMcqRoute
  '/api/kb/build-graph': typeof ApiKbBuildGraphRoute
  '/api/kb/ingest-github': typeof ApiKbIngestGithubRoute
  '/api/kb/ingest-url': typeof ApiKbIngestUrlRoute
  '/api/notebook/runtime': typeof ApiNotebookRuntimeRouteWithChildren
  '/api/skills/generate': typeof ApiSkillsGenerateRoute
  '/api/swarm/run': typeof ApiSwarmRunRoute
  '/api/templates/provision': typeof ApiTemplatesProvisionRoute
  '/api/warehouse/query': typeof ApiWarehouseQueryRoute
  '/api/warehouse/schema': typeof ApiWarehouseSchemaRoute
  '/embed/agent/$key': typeof EmbedAgentKeyRoute
  '/embed/bi/$key': typeof EmbedBiKeyRoute
  '/embed/swarm/$key': typeof EmbedSwarmKeyRoute
  '/share/bi/$slug': typeof ShareBiSlugRoute
  '/analytics/observability/$runId': typeof AuthenticatedAnalyticsObservabilityRunIdRoute
  '/notebooks/py/$pyNotebookId': typeof AuthenticatedNotebooksPyPyNotebookIdRoute
  '/notebooks/sample/$sampleSlug': typeof AuthenticatedNotebooksSampleSampleSlugRoute
  '/api/notebook/runtime/reap': typeof ApiNotebookRuntimeReapRoute
  '/api/notebook/runtime/result': typeof ApiNotebookRuntimeResultRoute
  '/api/notebook/runtime/source': typeof ApiNotebookRuntimeSourceRoute
  '/api/public/hooks/generate-exam-set': typeof ApiPublicHooksGenerateExamSetRoute
  '/api/public/hooks/refresh-model-registry': typeof ApiPublicHooksRefreshModelRegistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/terms': typeof TermsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/bi': typeof AuthenticatedBiRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-sql': typeof AuthenticatedDataSqlRoute
  '/_authenticated/embeds': typeof AuthenticatedEmbedsRoute
  '/_authenticated/image-playground': typeof AuthenticatedImagePlaygroundRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/mcp': typeof AuthenticatedMcpRoute
  '/_authenticated/model-registry': typeof AuthenticatedModelRegistryRoute
  '/_authenticated/notebooks': typeof AuthenticatedNotebooksRouteWithChildren
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute
  '/_authenticated/prompt-compare': typeof AuthenticatedPromptCompareRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/secrets': typeof AuthenticatedSecretsRoute
  '/_authenticated/semantics': typeof AuthenticatedSemanticsRoute
  '/_authenticated/skills': typeof AuthenticatedSkillsRoute
  '/_authenticated/swarms': typeof AuthenticatedSwarmsRoute
  '/_authenticated/traces': typeof AuthenticatedTracesRoute
  '/api/a2a': typeof ApiA2aRoute
  '/api/bi': typeof ApiBiRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/embed': typeof ApiEmbedRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/python-chat': typeof ApiPythonChatRoute
  '/api/python-kb': typeof ApiPythonKbRoute
  '/docs/account': typeof DocsAccountRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/analytics': typeof DocsAnalyticsRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/debugging': typeof DocsDebuggingRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/notebooks': typeof DocsNotebooksRoute
  '/docs/playground': typeof DocsPlaygroundRoute
  '/docs/skills': typeof DocsSkillsRoute
  '/docs/swarms': typeof DocsSwarmsRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/admin/iam': typeof AuthenticatedAdminIamRoute
  '/_authenticated/admin/runtime': typeof AuthenticatedAdminRuntimeRoute
  '/_authenticated/analytics_/observability': typeof AuthenticatedAnalyticsObservabilityRouteWithChildren
  '/_authenticated/bi_/$dashboardId': typeof AuthenticatedBiDashboardIdRoute
  '/api/auth/sso-config': typeof ApiAuthSsoConfigRoute
  '/api/bi/cron': typeof ApiBiCronRoute
  '/api/certificate/$id': typeof ApiCertificateIdRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/embed/chat': typeof ApiEmbedChatRoute
  '/api/exam/evaluate': typeof ApiExamEvaluateRoute
  '/api/exam/start': typeof ApiExamStartRoute
  '/api/exam/submit-mcq': typeof ApiExamSubmitMcqRoute
  '/api/kb/build-graph': typeof ApiKbBuildGraphRoute
  '/api/kb/ingest-github': typeof ApiKbIngestGithubRoute
  '/api/kb/ingest-url': typeof ApiKbIngestUrlRoute
  '/api/notebook/runtime': typeof ApiNotebookRuntimeRouteWithChildren
  '/api/skills/generate': typeof ApiSkillsGenerateRoute
  '/api/swarm/run': typeof ApiSwarmRunRoute
  '/api/templates/provision': typeof ApiTemplatesProvisionRoute
  '/api/warehouse/query': typeof ApiWarehouseQueryRoute
  '/api/warehouse/schema': typeof ApiWarehouseSchemaRoute
  '/embed/agent/$key': typeof EmbedAgentKeyRoute
  '/embed/bi/$key': typeof EmbedBiKeyRoute
  '/embed/swarm/$key': typeof EmbedSwarmKeyRoute
  '/share/bi/$slug': typeof ShareBiSlugRoute
  '/_authenticated/analytics_/observability/$runId': typeof AuthenticatedAnalyticsObservabilityRunIdRoute
  '/_authenticated/notebooks/py/$pyNotebookId': typeof AuthenticatedNotebooksPyPyNotebookIdRoute
  '/_authenticated/notebooks/sample/$sampleSlug': typeof AuthenticatedNotebooksSampleSampleSlugRoute
  '/api/notebook/runtime/reap': typeof ApiNotebookRuntimeReapRoute
  '/api/notebook/runtime/result': typeof ApiNotebookRuntimeResultRoute
  '/api/notebook/runtime/source': typeof ApiNotebookRuntimeSourceRoute
  '/api/public/hooks/generate-exam-set': typeof ApiPublicHooksGenerateExamSetRoute
  '/api/public/hooks/refresh-model-registry': typeof ApiPublicHooksRefreshModelRegistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/docs'
    | '/index'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/terms'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/bi'
    | '/budgets'
    | '/dashboard'
    | '/data-sql'
    | '/embeds'
    | '/image-playground'
    | '/integrations'
    | '/knowledge'
    | '/mcp'
    | '/model-registry'
    | '/notebooks'
    | '/playground'
    | '/prompt-compare'
    | '/prompts'
    | '/secrets'
    | '/semantics'
    | '/skills'
    | '/swarms'
    | '/traces'
    | '/api/a2a'
    | '/api/bi'
    | '/api/chat'
    | '/api/contact'
    | '/api/embed'
    | '/api/health'
    | '/api/python-chat'
    | '/api/python-kb'
    | '/docs/account'
    | '/docs/agents'
    | '/docs/analytics'
    | '/docs/dashboard'
    | '/docs/debugging'
    | '/docs/integrations'
    | '/docs/notebooks'
    | '/docs/playground'
    | '/docs/skills'
    | '/docs/swarms'
    | '/email/unsubscribe'
    | '/verify/$code'
    | '/docs/'
    | '/admin/iam'
    | '/admin/runtime'
    | '/analytics/observability'
    | '/bi/$dashboardId'
    | '/api/auth/sso-config'
    | '/api/bi/cron'
    | '/api/certificate/$id'
    | '/api/email/send'
    | '/api/embed/chat'
    | '/api/exam/evaluate'
    | '/api/exam/start'
    | '/api/exam/submit-mcq'
    | '/api/kb/build-graph'
    | '/api/kb/ingest-github'
    | '/api/kb/ingest-url'
    | '/api/notebook/runtime'
    | '/api/skills/generate'
    | '/api/swarm/run'
    | '/api/templates/provision'
    | '/api/warehouse/query'
    | '/api/warehouse/schema'
    | '/embed/agent/$key'
    | '/embed/bi/$key'
    | '/embed/swarm/$key'
    | '/share/bi/$slug'
    | '/analytics/observability/$runId'
    | '/notebooks/py/$pyNotebookId'
    | '/notebooks/sample/$sampleSlug'
    | '/api/notebook/runtime/reap'
    | '/api/notebook/runtime/result'
    | '/api/notebook/runtime/source'
    | '/api/public/hooks/generate-exam-set'
    | '/api/public/hooks/refresh-model-registry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/index'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/terms'
    | '/account'
    | '/agents'
    | '/analytics'
    | '/audit'
    | '/bi'
    | '/budgets'
    | '/dashboard'
    | '/data-sql'
    | '/embeds'
    | '/image-playground'
    | '/integrations'
    | '/knowledge'
    | '/mcp'
    | '/model-registry'
    | '/notebooks'
    | '/playground'
    | '/prompt-compare'
    | '/prompts'
    | '/secrets'
    | '/semantics'
    | '/skills'
    | '/swarms'
    | '/traces'
    | '/api/a2a'
    | '/api/bi'
    | '/api/chat'
    | '/api/contact'
    | '/api/embed'
    | '/api/health'
    | '/api/python-chat'
    | '/api/python-kb'
    | '/docs/account'
    | '/docs/agents'
    | '/docs/analytics'
    | '/docs/dashboard'
    | '/docs/debugging'
    | '/docs/integrations'
    | '/docs/notebooks'
    | '/docs/playground'
    | '/docs/skills'
    | '/docs/swarms'
    | '/email/unsubscribe'
    | '/verify/$code'
    | '/docs'
    | '/admin/iam'
    | '/admin/runtime'
    | '/analytics/observability'
    | '/bi/$dashboardId'
    | '/api/auth/sso-config'
    | '/api/bi/cron'
    | '/api/certificate/$id'
    | '/api/email/send'
    | '/api/embed/chat'
    | '/api/exam/evaluate'
    | '/api/exam/start'
    | '/api/exam/submit-mcq'
    | '/api/kb/build-graph'
    | '/api/kb/ingest-github'
    | '/api/kb/ingest-url'
    | '/api/notebook/runtime'
    | '/api/skills/generate'
    | '/api/swarm/run'
    | '/api/templates/provision'
    | '/api/warehouse/query'
    | '/api/warehouse/schema'
    | '/embed/agent/$key'
    | '/embed/bi/$key'
    | '/embed/swarm/$key'
    | '/share/bi/$slug'
    | '/analytics/observability/$runId'
    | '/notebooks/py/$pyNotebookId'
    | '/notebooks/sample/$sampleSlug'
    | '/api/notebook/runtime/reap'
    | '/api/notebook/runtime/result'
    | '/api/notebook/runtime/source'
    | '/api/public/hooks/generate-exam-set'
    | '/api/public/hooks/refresh-model-registry'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/docs'
    | '/index'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/terms'
    | '/_authenticated/account'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/audit'
    | '/_authenticated/bi'
    | '/_authenticated/budgets'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-sql'
    | '/_authenticated/embeds'
    | '/_authenticated/image-playground'
    | '/_authenticated/integrations'
    | '/_authenticated/knowledge'
    | '/_authenticated/mcp'
    | '/_authenticated/model-registry'
    | '/_authenticated/notebooks'
    | '/_authenticated/playground'
    | '/_authenticated/prompt-compare'
    | '/_authenticated/prompts'
    | '/_authenticated/secrets'
    | '/_authenticated/semantics'
    | '/_authenticated/skills'
    | '/_authenticated/swarms'
    | '/_authenticated/traces'
    | '/api/a2a'
    | '/api/bi'
    | '/api/chat'
    | '/api/contact'
    | '/api/embed'
    | '/api/health'
    | '/api/python-chat'
    | '/api/python-kb'
    | '/docs/account'
    | '/docs/agents'
    | '/docs/analytics'
    | '/docs/dashboard'
    | '/docs/debugging'
    | '/docs/integrations'
    | '/docs/notebooks'
    | '/docs/playground'
    | '/docs/skills'
    | '/docs/swarms'
    | '/email/unsubscribe'
    | '/verify/$code'
    | '/docs/'
    | '/_authenticated/admin/iam'
    | '/_authenticated/admin/runtime'
    | '/_authenticated/analytics_/observability'
    | '/_authenticated/bi_/$dashboardId'
    | '/api/auth/sso-config'
    | '/api/bi/cron'
    | '/api/certificate/$id'
    | '/api/email/send'
    | '/api/embed/chat'
    | '/api/exam/evaluate'
    | '/api/exam/start'
    | '/api/exam/submit-mcq'
    | '/api/kb/build-graph'
    | '/api/kb/ingest-github'
    | '/api/kb/ingest-url'
    | '/api/notebook/runtime'
    | '/api/skills/generate'
    | '/api/swarm/run'
    | '/api/templates/provision'
    | '/api/warehouse/query'
    | '/api/warehouse/schema'
    | '/embed/agent/$key'
    | '/embed/bi/$key'
    | '/embed/swarm/$key'
    | '/share/bi/$slug'
    | '/_authenticated/analytics_/observability/$runId'
    | '/_authenticated/notebooks/py/$pyNotebookId'
    | '/_authenticated/notebooks/sample/$sampleSlug'
    | '/api/notebook/runtime/reap'
    | '/api/notebook/runtime/result'
    | '/api/notebook/runtime/source'
    | '/api/public/hooks/generate-exam-set'
    | '/api/public/hooks/refresh-model-registry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  TermsRoute: typeof TermsRoute
  ApiA2aRoute: typeof ApiA2aRoute
  ApiBiRoute: typeof ApiBiRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiEmbedRoute: typeof ApiEmbedRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPythonChatRoute: typeof ApiPythonChatRoute
  ApiPythonKbRoute: typeof ApiPythonKbRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  ApiAuthSsoConfigRoute: typeof ApiAuthSsoConfigRoute
  ApiCertificateIdRoute: typeof ApiCertificateIdRoute
  ApiEmailSendRoute: typeof ApiEmailSendRoute
  ApiExamEvaluateRoute: typeof ApiExamEvaluateRoute
  ApiExamStartRoute: typeof ApiExamStartRoute
  ApiExamSubmitMcqRoute: typeof ApiExamSubmitMcqRoute
  ApiKbBuildGraphRoute: typeof ApiKbBuildGraphRoute
  ApiKbIngestGithubRoute: typeof ApiKbIngestGithubRoute
  ApiKbIngestUrlRoute: typeof ApiKbIngestUrlRoute
  ApiNotebookRuntimeRoute: typeof ApiNotebookRuntimeRouteWithChildren
  ApiSkillsGenerateRoute: typeof ApiSkillsGenerateRoute
  ApiSwarmRunRoute: typeof ApiSwarmRunRoute
  ApiTemplatesProvisionRoute: typeof ApiTemplatesProvisionRoute
  ApiWarehouseQueryRoute: typeof ApiWarehouseQueryRoute
  ApiWarehouseSchemaRoute: typeof ApiWarehouseSchemaRoute
  EmbedAgentKeyRoute: typeof EmbedAgentKeyRoute
  EmbedBiKeyRoute: typeof EmbedBiKeyRoute
  EmbedSwarmKeyRoute: typeof EmbedSwarmKeyRoute
  ShareBiSlugRoute: typeof ShareBiSlugRoute
  ApiPublicHooksGenerateExamSetRoute: typeof ApiPublicHooksGenerateExamSetRoute
  ApiPublicHooksRefreshModelRegistryRoute: typeof ApiPublicHooksRefreshModelRegistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/swarms': {
      id: '/docs/swarms'
      path: '/swarms'
      fullPath: '/docs/swarms'
      preLoaderRoute: typeof DocsSwarmsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/skills': {
      id: '/docs/skills'
      path: '/skills'
      fullPath: '/docs/skills'
      preLoaderRoute: typeof DocsSkillsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/playground': {
      id: '/docs/playground'
      path: '/playground'
      fullPath: '/docs/playground'
      preLoaderRoute: typeof DocsPlaygroundRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/notebooks': {
      id: '/docs/notebooks'
      path: '/notebooks'
      fullPath: '/docs/notebooks'
      preLoaderRoute: typeof DocsNotebooksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/integrations': {
      id: '/docs/integrations'
      path: '/integrations'
      fullPath: '/docs/integrations'
      preLoaderRoute: typeof DocsIntegrationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/debugging': {
      id: '/docs/debugging'
      path: '/debugging'
      fullPath: '/docs/debugging'
      preLoaderRoute: typeof DocsDebuggingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dashboard': {
      id: '/docs/dashboard'
      path: '/dashboard'
      fullPath: '/docs/dashboard'
      preLoaderRoute: typeof DocsDashboardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/analytics': {
      id: '/docs/analytics'
      path: '/analytics'
      fullPath: '/docs/analytics'
      preLoaderRoute: typeof DocsAnalyticsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/account': {
      id: '/docs/account'
      path: '/account'
      fullPath: '/docs/account'
      preLoaderRoute: typeof DocsAccountRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/python-kb': {
      id: '/api/python-kb'
      path: '/api/python-kb'
      fullPath: '/api/python-kb'
      preLoaderRoute: typeof ApiPythonKbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/python-chat': {
      id: '/api/python-chat'
      path: '/api/python-chat'
      fullPath: '/api/python-chat'
      preLoaderRoute: typeof ApiPythonChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed': {
      id: '/api/embed'
      path: '/api/embed'
      fullPath: '/api/embed'
      preLoaderRoute: typeof ApiEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bi': {
      id: '/api/bi'
      path: '/api/bi'
      fullPath: '/api/bi'
      preLoaderRoute: typeof ApiBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/a2a': {
      id: '/api/a2a'
      path: '/api/a2a'
      fullPath: '/api/a2a'
      preLoaderRoute: typeof ApiA2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traces': {
      id: '/_authenticated/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AuthenticatedTracesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/swarms': {
      id: '/_authenticated/swarms'
      path: '/swarms'
      fullPath: '/swarms'
      preLoaderRoute: typeof AuthenticatedSwarmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/skills': {
      id: '/_authenticated/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedSkillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/semantics': {
      id: '/_authenticated/semantics'
      path: '/semantics'
      fullPath: '/semantics'
      preLoaderRoute: typeof AuthenticatedSemanticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/secrets': {
      id: '/_authenticated/secrets'
      path: '/secrets'
      fullPath: '/secrets'
      preLoaderRoute: typeof AuthenticatedSecretsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prompt-compare': {
      id: '/_authenticated/prompt-compare'
      path: '/prompt-compare'
      fullPath: '/prompt-compare'
      preLoaderRoute: typeof AuthenticatedPromptCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notebooks': {
      id: '/_authenticated/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof AuthenticatedNotebooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-registry': {
      id: '/_authenticated/model-registry'
      path: '/model-registry'
      fullPath: '/model-registry'
      preLoaderRoute: typeof AuthenticatedModelRegistryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mcp': {
      id: '/_authenticated/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof AuthenticatedMcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/image-playground': {
      id: '/_authenticated/image-playground'
      path: '/image-playground'
      fullPath: '/image-playground'
      preLoaderRoute: typeof AuthenticatedImagePlaygroundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/embeds': {
      id: '/_authenticated/embeds'
      path: '/embeds'
      fullPath: '/embeds'
      preLoaderRoute: typeof AuthenticatedEmbedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-sql': {
      id: '/_authenticated/data-sql'
      path: '/data-sql'
      fullPath: '/data-sql'
      preLoaderRoute: typeof AuthenticatedDataSqlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bi': {
      id: '/_authenticated/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof AuthenticatedBiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/share/bi/$slug': {
      id: '/share/bi/$slug'
      path: '/share/bi/$slug'
      fullPath: '/share/bi/$slug'
      preLoaderRoute: typeof ShareBiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/swarm/$key': {
      id: '/embed/swarm/$key'
      path: '/embed/swarm/$key'
      fullPath: '/embed/swarm/$key'
      preLoaderRoute: typeof EmbedSwarmKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/bi/$key': {
      id: '/embed/bi/$key'
      path: '/embed/bi/$key'
      fullPath: '/embed/bi/$key'
      preLoaderRoute: typeof EmbedBiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/agent/$key': {
      id: '/embed/agent/$key'
      path: '/embed/agent/$key'
      fullPath: '/embed/agent/$key'
      preLoaderRoute: typeof EmbedAgentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warehouse/schema': {
      id: '/api/warehouse/schema'
      path: '/api/warehouse/schema'
      fullPath: '/api/warehouse/schema'
      preLoaderRoute: typeof ApiWarehouseSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warehouse/query': {
      id: '/api/warehouse/query'
      path: '/api/warehouse/query'
      fullPath: '/api/warehouse/query'
      preLoaderRoute: typeof ApiWarehouseQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/provision': {
      id: '/api/templates/provision'
      path: '/api/templates/provision'
      fullPath: '/api/templates/provision'
      preLoaderRoute: typeof ApiTemplatesProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swarm/run': {
      id: '/api/swarm/run'
      path: '/api/swarm/run'
      fullPath: '/api/swarm/run'
      preLoaderRoute: typeof ApiSwarmRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills/generate': {
      id: '/api/skills/generate'
      path: '/api/skills/generate'
      fullPath: '/api/skills/generate'
      preLoaderRoute: typeof ApiSkillsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebook/runtime': {
      id: '/api/notebook/runtime'
      path: '/api/notebook/runtime'
      fullPath: '/api/notebook/runtime'
      preLoaderRoute: typeof ApiNotebookRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/ingest-url': {
      id: '/api/kb/ingest-url'
      path: '/api/kb/ingest-url'
      fullPath: '/api/kb/ingest-url'
      preLoaderRoute: typeof ApiKbIngestUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/ingest-github': {
      id: '/api/kb/ingest-github'
      path: '/api/kb/ingest-github'
      fullPath: '/api/kb/ingest-github'
      preLoaderRoute: typeof ApiKbIngestGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kb/build-graph': {
      id: '/api/kb/build-graph'
      path: '/api/kb/build-graph'
      fullPath: '/api/kb/build-graph'
      preLoaderRoute: typeof ApiKbBuildGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam/submit-mcq': {
      id: '/api/exam/submit-mcq'
      path: '/api/exam/submit-mcq'
      fullPath: '/api/exam/submit-mcq'
      preLoaderRoute: typeof ApiExamSubmitMcqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam/start': {
      id: '/api/exam/start'
      path: '/api/exam/start'
      fullPath: '/api/exam/start'
      preLoaderRoute: typeof ApiExamStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam/evaluate': {
      id: '/api/exam/evaluate'
      path: '/api/exam/evaluate'
      fullPath: '/api/exam/evaluate'
      preLoaderRoute: typeof ApiExamEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/embed/chat': {
      id: '/api/embed/chat'
      path: '/chat'
      fullPath: '/api/embed/chat'
      preLoaderRoute: typeof ApiEmbedChatRouteImport
      parentRoute: typeof ApiEmbedRoute
    }
    '/api/email/send': {
      id: '/api/email/send'
      path: '/api/email/send'
      fullPath: '/api/email/send'
      preLoaderRoute: typeof ApiEmailSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificate/$id': {
      id: '/api/certificate/$id'
      path: '/api/certificate/$id'
      fullPath: '/api/certificate/$id'
      preLoaderRoute: typeof ApiCertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bi/cron': {
      id: '/api/bi/cron'
      path: '/cron'
      fullPath: '/api/bi/cron'
      preLoaderRoute: typeof ApiBiCronRouteImport
      parentRoute: typeof ApiBiRoute
    }
    '/api/auth/sso-config': {
      id: '/api/auth/sso-config'
      path: '/api/auth/sso-config'
      fullPath: '/api/auth/sso-config'
      preLoaderRoute: typeof ApiAuthSsoConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bi_/$dashboardId': {
      id: '/_authenticated/bi_/$dashboardId'
      path: '/bi/$dashboardId'
      fullPath: '/bi/$dashboardId'
      preLoaderRoute: typeof AuthenticatedBiDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics_/observability': {
      id: '/_authenticated/analytics_/observability'
      path: '/analytics/observability'
      fullPath: '/analytics/observability'
      preLoaderRoute: typeof AuthenticatedAnalyticsObservabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/runtime': {
      id: '/_authenticated/admin/runtime'
      path: '/admin/runtime'
      fullPath: '/admin/runtime'
      preLoaderRoute: typeof AuthenticatedAdminRuntimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/iam': {
      id: '/_authenticated/admin/iam'
      path: '/admin/iam'
      fullPath: '/admin/iam'
      preLoaderRoute: typeof AuthenticatedAdminIamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/refresh-model-registry': {
      id: '/api/public/hooks/refresh-model-registry'
      path: '/api/public/hooks/refresh-model-registry'
      fullPath: '/api/public/hooks/refresh-model-registry'
      preLoaderRoute: typeof ApiPublicHooksRefreshModelRegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-exam-set': {
      id: '/api/public/hooks/generate-exam-set'
      path: '/api/public/hooks/generate-exam-set'
      fullPath: '/api/public/hooks/generate-exam-set'
      preLoaderRoute: typeof ApiPublicHooksGenerateExamSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebook/runtime/source': {
      id: '/api/notebook/runtime/source'
      path: '/source'
      fullPath: '/api/notebook/runtime/source'
      preLoaderRoute: typeof ApiNotebookRuntimeSourceRouteImport
      parentRoute: typeof ApiNotebookRuntimeRoute
    }
    '/api/notebook/runtime/result': {
      id: '/api/notebook/runtime/result'
      path: '/result'
      fullPath: '/api/notebook/runtime/result'
      preLoaderRoute: typeof ApiNotebookRuntimeResultRouteImport
      parentRoute: typeof ApiNotebookRuntimeRoute
    }
    '/api/notebook/runtime/reap': {
      id: '/api/notebook/runtime/reap'
      path: '/reap'
      fullPath: '/api/notebook/runtime/reap'
      preLoaderRoute: typeof ApiNotebookRuntimeReapRouteImport
      parentRoute: typeof ApiNotebookRuntimeRoute
    }
    '/_authenticated/notebooks/sample/$sampleSlug': {
      id: '/_authenticated/notebooks/sample/$sampleSlug'
      path: '/sample/$sampleSlug'
      fullPath: '/notebooks/sample/$sampleSlug'
      preLoaderRoute: typeof AuthenticatedNotebooksSampleSampleSlugRouteImport
      parentRoute: typeof AuthenticatedNotebooksRoute
    }
    '/_authenticated/notebooks/py/$pyNotebookId': {
      id: '/_authenticated/notebooks/py/$pyNotebookId'
      path: '/py/$pyNotebookId'
      fullPath: '/notebooks/py/$pyNotebookId'
      preLoaderRoute: typeof AuthenticatedNotebooksPyPyNotebookIdRouteImport
      parentRoute: typeof AuthenticatedNotebooksRoute
    }
    '/_authenticated/analytics_/observability/$runId': {
      id: '/_authenticated/analytics_/observability/$runId'
      path: '/$runId'
      fullPath: '/analytics/observability/$runId'
      preLoaderRoute: typeof AuthenticatedAnalyticsObservabilityRunIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsObservabilityRoute
    }
  }
}

interface AuthenticatedNotebooksRouteChildren {
  AuthenticatedNotebooksPyPyNotebookIdRoute: typeof AuthenticatedNotebooksPyPyNotebookIdRoute
  AuthenticatedNotebooksSampleSampleSlugRoute: typeof AuthenticatedNotebooksSampleSampleSlugRoute
}

const AuthenticatedNotebooksRouteChildren: AuthenticatedNotebooksRouteChildren =
  {
    AuthenticatedNotebooksPyPyNotebookIdRoute:
      AuthenticatedNotebooksPyPyNotebookIdRoute,
    AuthenticatedNotebooksSampleSampleSlugRoute:
      AuthenticatedNotebooksSampleSampleSlugRoute,
  }

const AuthenticatedNotebooksRouteWithChildren =
  AuthenticatedNotebooksRoute._addFileChildren(
    AuthenticatedNotebooksRouteChildren,
  )

interface AuthenticatedAnalyticsObservabilityRouteChildren {
  AuthenticatedAnalyticsObservabilityRunIdRoute: typeof AuthenticatedAnalyticsObservabilityRunIdRoute
}

const AuthenticatedAnalyticsObservabilityRouteChildren: AuthenticatedAnalyticsObservabilityRouteChildren =
  {
    AuthenticatedAnalyticsObservabilityRunIdRoute:
      AuthenticatedAnalyticsObservabilityRunIdRoute,
  }

const AuthenticatedAnalyticsObservabilityRouteWithChildren =
  AuthenticatedAnalyticsObservabilityRoute._addFileChildren(
    AuthenticatedAnalyticsObservabilityRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBiRoute: typeof AuthenticatedBiRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataSqlRoute: typeof AuthenticatedDataSqlRoute
  AuthenticatedEmbedsRoute: typeof AuthenticatedEmbedsRoute
  AuthenticatedImagePlaygroundRoute: typeof AuthenticatedImagePlaygroundRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedMcpRoute: typeof AuthenticatedMcpRoute
  AuthenticatedModelRegistryRoute: typeof AuthenticatedModelRegistryRoute
  AuthenticatedNotebooksRoute: typeof AuthenticatedNotebooksRouteWithChildren
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute
  AuthenticatedPromptCompareRoute: typeof AuthenticatedPromptCompareRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedSecretsRoute: typeof AuthenticatedSecretsRoute
  AuthenticatedSemanticsRoute: typeof AuthenticatedSemanticsRoute
  AuthenticatedSkillsRoute: typeof AuthenticatedSkillsRoute
  AuthenticatedSwarmsRoute: typeof AuthenticatedSwarmsRoute
  AuthenticatedTracesRoute: typeof AuthenticatedTracesRoute
  AuthenticatedAdminIamRoute: typeof AuthenticatedAdminIamRoute
  AuthenticatedAdminRuntimeRoute: typeof AuthenticatedAdminRuntimeRoute
  AuthenticatedAnalyticsObservabilityRoute: typeof AuthenticatedAnalyticsObservabilityRouteWithChildren
  AuthenticatedBiDashboardIdRoute: typeof AuthenticatedBiDashboardIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBiRoute: AuthenticatedBiRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataSqlRoute: AuthenticatedDataSqlRoute,
  AuthenticatedEmbedsRoute: AuthenticatedEmbedsRoute,
  AuthenticatedImagePlaygroundRoute: AuthenticatedImagePlaygroundRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedMcpRoute: AuthenticatedMcpRoute,
  AuthenticatedModelRegistryRoute: AuthenticatedModelRegistryRoute,
  AuthenticatedNotebooksRoute: AuthenticatedNotebooksRouteWithChildren,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedPromptCompareRoute: AuthenticatedPromptCompareRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedSecretsRoute: AuthenticatedSecretsRoute,
  AuthenticatedSemanticsRoute: AuthenticatedSemanticsRoute,
  AuthenticatedSkillsRoute: AuthenticatedSkillsRoute,
  AuthenticatedSwarmsRoute: AuthenticatedSwarmsRoute,
  AuthenticatedTracesRoute: AuthenticatedTracesRoute,
  AuthenticatedAdminIamRoute: AuthenticatedAdminIamRoute,
  AuthenticatedAdminRuntimeRoute: AuthenticatedAdminRuntimeRoute,
  AuthenticatedAnalyticsObservabilityRoute:
    AuthenticatedAnalyticsObservabilityRouteWithChildren,
  AuthenticatedBiDashboardIdRoute: AuthenticatedBiDashboardIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsAccountRoute: typeof DocsAccountRoute
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsAnalyticsRoute: typeof DocsAnalyticsRoute
  DocsDashboardRoute: typeof DocsDashboardRoute
  DocsDebuggingRoute: typeof DocsDebuggingRoute
  DocsIntegrationsRoute: typeof DocsIntegrationsRoute
  DocsNotebooksRoute: typeof DocsNotebooksRoute
  DocsPlaygroundRoute: typeof DocsPlaygroundRoute
  DocsSkillsRoute: typeof DocsSkillsRoute
  DocsSwarmsRoute: typeof DocsSwarmsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAccountRoute: DocsAccountRoute,
  DocsAgentsRoute: DocsAgentsRoute,
  DocsAnalyticsRoute: DocsAnalyticsRoute,
  DocsDashboardRoute: DocsDashboardRoute,
  DocsDebuggingRoute: DocsDebuggingRoute,
  DocsIntegrationsRoute: DocsIntegrationsRoute,
  DocsNotebooksRoute: DocsNotebooksRoute,
  DocsPlaygroundRoute: DocsPlaygroundRoute,
  DocsSkillsRoute: DocsSkillsRoute,
  DocsSwarmsRoute: DocsSwarmsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiBiRouteChildren {
  ApiBiCronRoute: typeof ApiBiCronRoute
}

const ApiBiRouteChildren: ApiBiRouteChildren = {
  ApiBiCronRoute: ApiBiCronRoute,
}

const ApiBiRouteWithChildren = ApiBiRoute._addFileChildren(ApiBiRouteChildren)

interface ApiEmbedRouteChildren {
  ApiEmbedChatRoute: typeof ApiEmbedChatRoute
}

const ApiEmbedRouteChildren: ApiEmbedRouteChildren = {
  ApiEmbedChatRoute: ApiEmbedChatRoute,
}

const ApiEmbedRouteWithChildren = ApiEmbedRoute._addFileChildren(
  ApiEmbedRouteChildren,
)

interface ApiNotebookRuntimeRouteChildren {
  ApiNotebookRuntimeReapRoute: typeof ApiNotebookRuntimeReapRoute
  ApiNotebookRuntimeResultRoute: typeof ApiNotebookRuntimeResultRoute
  ApiNotebookRuntimeSourceRoute: typeof ApiNotebookRuntimeSourceRoute
}

const ApiNotebookRuntimeRouteChildren: ApiNotebookRuntimeRouteChildren = {
  ApiNotebookRuntimeReapRoute: ApiNotebookRuntimeReapRoute,
  ApiNotebookRuntimeResultRoute: ApiNotebookRuntimeResultRoute,
  ApiNotebookRuntimeSourceRoute: ApiNotebookRuntimeSourceRoute,
}

const ApiNotebookRuntimeRouteWithChildren =
  ApiNotebookRuntimeRoute._addFileChildren(ApiNotebookRuntimeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  TermsRoute: TermsRoute,
  ApiA2aRoute: ApiA2aRoute,
  ApiBiRoute: ApiBiRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiEmbedRoute: ApiEmbedRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiPythonChatRoute: ApiPythonChatRoute,
  ApiPythonKbRoute: ApiPythonKbRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  ApiAuthSsoConfigRoute: ApiAuthSsoConfigRoute,
  ApiCertificateIdRoute: ApiCertificateIdRoute,
  ApiEmailSendRoute: ApiEmailSendRoute,
  ApiExamEvaluateRoute: ApiExamEvaluateRoute,
  ApiExamStartRoute: ApiExamStartRoute,
  ApiExamSubmitMcqRoute: ApiExamSubmitMcqRoute,
  ApiKbBuildGraphRoute: ApiKbBuildGraphRoute,
  ApiKbIngestGithubRoute: ApiKbIngestGithubRoute,
  ApiKbIngestUrlRoute: ApiKbIngestUrlRoute,
  ApiNotebookRuntimeRoute: ApiNotebookRuntimeRouteWithChildren,
  ApiSkillsGenerateRoute: ApiSkillsGenerateRoute,
  ApiSwarmRunRoute: ApiSwarmRunRoute,
  ApiTemplatesProvisionRoute: ApiTemplatesProvisionRoute,
  ApiWarehouseQueryRoute: ApiWarehouseQueryRoute,
  ApiWarehouseSchemaRoute: ApiWarehouseSchemaRoute,
  EmbedAgentKeyRoute: EmbedAgentKeyRoute,
  EmbedBiKeyRoute: EmbedBiKeyRoute,
  EmbedSwarmKeyRoute: EmbedSwarmKeyRoute,
  ShareBiSlugRoute: ShareBiSlugRoute,
  ApiPublicHooksGenerateExamSetRoute: ApiPublicHooksGenerateExamSetRoute,
  ApiPublicHooksRefreshModelRegistryRoute:
    ApiPublicHooksRefreshModelRegistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
